In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('/home/rk/orgs_final1.csv')

In [3]:
data.label.replace(('successful', 'unsucessful'), (1, 0), inplace=True)
data['employee_count']
data.shape

(107536, 14)

In [4]:
import numpy as np
dict_lower={'1-10':1, '10000+':10000, '251-500':251, '11-50':11, '1001-5000':1001, '501-1000':501,
       'unknown':np.nan, '51-100':51, '101-250':101, '5001-10000':5001}
dict_higher={'1-10':10, '10000+':1000000, '251-500':500, '11-50':50, '1001-5000':5000, '501-1000':1000,
       'unknown':np.nan, '51-100':100, '101-250':250, '5001-10000':10000}

In [5]:
data_temp=data
data_temp.head(2)

,company_name,employee_count,location,no_of_founders,no_of_funding_rounds,no_of_board_members,description,amount_raised,label,industry_vertical,age_months,last_funding_status,no_of_investors,social_media_presence
0,Grown Ocean,1-10,northeast,0,1,0,Grown Ocean is the mobile app for planning you...,250000.0,0,Travel and Tourism,52,seed,0,1.0
1,Adaptive Media,10000+,west,0,1,0,Adaptive Media is an audience and content mone...,15000000.0,0,Internet Services,88,series_unknown,0,1.0

In [6]:
'''from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()  
print(data['location'].unique())
data_temp['location']= label_encoder.fit_transform(data_temp['location']) 
data_temp['employee_count']= label_encoder.fit_transform(data_temp['employee_count']) 
data_temp['industry_vertical']= label_encoder.fit_transform(data_temp['industry_vertical']) 
data_temp['last_funding_status']= label_encoder.fit_transform(data_temp['last_funding_status']) 
data_temp.label.replace(('successful', 'unsucessful'), (1, 0), inplace=True)
'''

"from sklearn import preprocessing\nlabel_encoder = preprocessing.LabelEncoder()  \nprint(data['location'].unique())\ndata_temp['location']= label_encoder.fit_transform(data_temp['location']) \ndata_temp['employee_count']= label_encoder.fit_transform(data_temp['employee_count']) \ndata_temp['industry_vertical']= label_encoder.fit_transform(data_temp['industry_vertical']) \ndata_temp['last_funding_status']= label_encoder.fit_transform(data_temp['last_funding_status']) \ndata_temp.label.replace(('successful', 'unsucessful'), (1, 0), inplace=True)\n"

In [7]:
for column in ['employee_count', 'location','industry_vertical','last_funding_status']:
    dummies = pd.get_dummies(data[column],prefix=column)
    data[dummies.columns] = dummies
data.head()

,company_name,employee_count,location,no_of_founders,no_of_funding_rounds,no_of_board_members,description,amount_raised,label,industry_vertical,...,last_funding_status_series_b,last_funding_status_series_c,last_funding_status_series_d,last_funding_status_series_e,last_funding_status_series_f,last_funding_status_series_g,last_funding_status_series_h,last_funding_status_series_i,last_funding_status_series_unknown,last_funding_status_undisclosed
0,Grown Ocean,1-10,northeast,0,1,0,Grown Ocean is the mobile app for planning you...,250000.0,0,Travel and Tourism,...,0,0,0,0,0,0,0,0,0,0
1,Adaptive Media,10000+,west,0,1,0,Adaptive Media is an audience and content mone...,15000000.0,0,Internet Services,...,0,0,0,0,0,0,0,0,1,0
2,Gazelle Lab,1-10,southeast,3,1,0,"Gazelle Lab is a TechStars Network member, men...",0.0,0,Financial Services,...,0,0,0,0,0,0,0,0,1,0
3,HealthAxis Group,251-500,southeast,0,1,0,The HealthAxis Group seeks to reboot healthcar...,57000000.0,0,Health Care,...,0,0,0,0,0,0,0,0,0,0
4,Wokrr,1-10,west,1,1,0,"Wokrr is based in San Jose, California, United...",1111.0,0,others,...,0,0,0,0,0,0,0,0,0,0

In [8]:
data.drop(columns=['employee_count', 'location','industry_vertical','last_funding_status','company_name','description'],inplace=True)
data.head()

,no_of_founders,no_of_funding_rounds,no_of_board_members,amount_raised,label,age_months,no_of_investors,social_media_presence,employee_count_1-10,employee_count_10000+,...,last_funding_status_series_b,last_funding_status_series_c,last_funding_status_series_d,last_funding_status_series_e,last_funding_status_series_f,last_funding_status_series_g,last_funding_status_series_h,last_funding_status_series_i,last_funding_status_series_unknown,last_funding_status_undisclosed
0,0,1,0,250000.0,0,52,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,15000000.0,0,88,0,1.0,0,1,...,0,0,0,0,0,0,0,0,1,0
2,3,1,0,0.0,0,93,1,1.0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,0,1,0,57000000.0,0,100,1,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,1111.0,0,40,0,0.0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
data.columns.values.tolist()

['no_of_founders',
 'no_of_funding_rounds',
 'no_of_board_members',
 'amount_raised',
 'label',
 'age_months',
 'no_of_investors',
 'social_media_presence',
 'employee_count_1-10',
 'employee_count_10000+',
 'employee_count_1001-5000',
 'employee_count_101-250',
 'employee_count_11-50',
 'employee_count_251-500',
 'employee_count_5001-10000',
 'employee_count_501-1000',
 'employee_count_51-100',
 'employee_count_unknown',
 'location_midwest',
 'location_northeast',
 'location_others',
 'location_southeast',
 'location_southwest',
 'location_west',
 'industry_vertical_Administrative Services',
 'industry_vertical_Advertising',
 'industry_vertical_Agriculture and Farming',
 'industry_vertical_Apps',
 'industry_vertical_Artificial Intelligence',
 'industry_vertical_Biotechnology',
 'industry_vertical_Clothing and Apparel',
 'industry_vertical_Commerce and Shopping',
 'industry_vertical_Community and Lifestyle',
 'industry_vertical_Consumer Electronics',
 'industry_vertical_Consumer Goods',
 'industry_vertical_Content and Publishing',
 'industry_vertical_Data and Analytics',
 'industry_vertical_Design',
 'industry_vertical_Education',
 'industry_vertical_Energy',
 'industry_vertical_Events',
 'industry_vertical_Financial Services',
 'industry_vertical_Food and Beverage',
 'industry_vertical_Gaming',
 'industry_vertical_Government and Military',
 'industry_vertical_Hardware',
 'industry_vertical_Health Care',
 'industry_vertical_Information Technology',
 'industry_vertical_Internet Services',
 'industry_vertical_Lending and Investments',
 'industry_vertical_Manufacturing',
 'industry_vertical_Media and Entertainment',
 'industry_vertical_Messaging and Telecommunications',
 'industry_vertical_Mobile',
 'industry_vertical_Music and Audio',
 'industry_vertical_Natural Resources',
 'industry_vertical_Navigation and Mapping',
 'industry_vertical_Payments',
 'industry_vertical_Platforms',
 'industry_vertical_Privacy and Security',
 'industry_vertical_Professional Services',
 'industry_vertical_Real Estate',
 'industry_vertical_Sales and Marketing',
 'industry_vertical_Science and Engineering',
 'industry_vertical_Software',
 'industry_vertical_Sports',
 'industry_vertical_Sustainability',
 'industry_vertical_Transportation',
 'industry_vertical_Travel and Tourism',
 'industry_vertical_Video',
 'industry_vertical_others',
 'last_funding_status_No_funding',
 'last_funding_status_angel',
 'last_funding_status_convertible_note',
 'last_funding_status_corporate_round',
 'last_funding_status_debt_financing',
 'last_funding_status_equity_crowdfunding',
 'last_funding_status_grant',
 'last_funding_status_initial_coin_offering',
 'last_funding_status_non_equity_assistance',
 'last_funding_status_post_ipo_debt',
 'last_funding_status_post_ipo_equity',
 'last_funding_status_pre_seed',
 'last_funding_status_private_equity',
 'last_funding_status_product_crowdfunding',
 'last_funding_status_secondary_market',
 'last_funding_status_seed',
 'last_funding_status_series_a',
 'last_funding_status_series_b',
 'last_funding_status_series_c',
 'last_funding_status_series_d',
 'last_funding_status_series_e',
 'last_funding_status_series_f',
 'last_funding_status_series_g',
 'last_funding_status_series_h',
 'last_funding_status_series_i',
 'last_funding_status_series_unknown',
 'last_funding_status_undisclosed']

In [10]:
data_temp=data

In [11]:
data_temp['label'].unique()

array([0, 1])

In [12]:
tot_1=data_temp['label'].value_counts()[1]
tot_0=data_temp['label'].value_counts()[0]
print(tot_0,tot_1)

99081 8455

In [13]:
data_temp.sort_values(by=['label'])

,no_of_founders,no_of_funding_rounds,no_of_board_members,amount_raised,label,age_months,no_of_investors,social_media_presence,employee_count_1-10,employee_count_10000+,...,last_funding_status_series_b,last_funding_status_series_c,last_funding_status_series_d,last_funding_status_series_e,last_funding_status_series_f,last_funding_status_series_g,last_funding_status_series_h,last_funding_status_series_i,last_funding_status_series_unknown,last_funding_status_undisclosed
0,0,1,0,250000.0,0,52,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70506,0,0,0,0.0,0,101,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70505,0,0,3,0.0,0,55,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70504,0,0,0,0.0,0,36,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70503,1,0,0,0.0,0,47,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70502,0,0,0,0.0,0,124,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
70501,0,0,0,0.0,0,100,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
70498,1,0,1,0.0,0,0,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
70497,2,0,0,0.0,0,88,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70496,0,0,0,0.0,0,88,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70495,0,0,0,0.0,0,76,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70494,0,0,0,0.0,0,64,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70493,0,0,0,0.0,0,124,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
70492,2,0,0,0.0,0,51,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70491,0,0,0,0.0,0,115,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70490,1,0,0,0.0,0,28,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70489,0,0,0,0.0,0,112,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
70488,0,0,0,0.0,0,100,0,0.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70487,0,0,0,0.0,0,14,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70486,0,0,0,0.0,0,51,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70485,0,0,0,0.0,0,76,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70484,0,0,0,0.0,0,92,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
70507,0,0,0,0.0,0,64,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
70483,0,0,0,0.0,0,69,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70508,0,0,0,0.0,0,136,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70510,1,0,0,0.0,0,80,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70533,0,0,0,0.0,0,44,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
70532,0,0,0,0.0,0,32,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
70531,2,0,0,0.0,0,136,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
70530,2,0,0,0.0,0,64,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83480,0,0,0,0.0,1,100,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
83476,1,0,0,0.0,1,124,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
97976,0,0,0,0.0,1,100,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
8965,3,4,0,15200000.0,1,280,21,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
83472,0,0,0,0.0,1,85,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
22440,2,1,0,34400000.0,1,52,5,1.0,0,0,...,0,0,0,0,0,0,0,0,1,0
9008,2,4,0,205000.0,1,87,4,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
9009,0,1,0,327260.0,1,76,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
59510,0,0,0,0.0,1,124,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
71348,0,0,0,0.0,1,110,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
22391,0,5,0,135799920.0,1,100,5,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
22393,1,4,0,3700000.0,1,77,11,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9037,0,1,0,30000000.0,1,76,5,1.0,0,1,...,0,0,0,0,0,0,0,0,0,0
9035,3,3,0,2300000.0,1,76,10,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9034,1,4,0,3174999.0,1,101,13,1.0,1,0,...,0,0,0,0,0,0,0,0,1,0
71355,0,0,0,0.0,1,124,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
97901,0,0,0,0.0,1,88,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
83525,0,0,0,0.0,1,88,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9029,0,1,0,3000000.0,1,88,1,1.0,0,0,...,0,0,0,0,0,0,0,0,1,0
22404,0,1,0,0.0,1,38,1,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
44794,0,0,0,0.0,1,136,0,1.0,1,0,...,0,0,0,0,0,0,0,0,0,0
9021,0,5,1,9249999.0,1,128,1,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9020,0,1,0,8000000.0,1,100,4,1.0,0,0,...,0,0,0,0,0,0,0,0,1,0
9019,1,4,0,2012948.0,1,100,1,1.0,0,0,...,0,0,0,0,0,0,0,0,1,0
97920,0,0,0,0.0,1,136,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
59513,0,0,0,0.0,1,124,0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0
22411,2,4,0,11375000.0,1,96,9,1.0,1,0,...,0,0,0,0,0,0,0,0,1,0
59511,1,0,0,0.0,1,53,0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9049,2,2,0,13600000.0,1,100,6,1.0,0,1,...,1,0,0,0,0,0,0,0,0,0
8408,0,1,0,0.0,1,100,1,1.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
unseuc_dataset=data_temp.loc[data_temp['label']==0]
unseuc_dataset.shape

(99081, 98)

In [15]:
succ_dataset=data_temp.loc[data_temp['label']==1]
succ_dataset.shape

(8455, 98)

In [16]:
percent_of0_data=tot_0/(tot_1+tot_0)
num1=percent_of0_data*len(unseuc_dataset)
num2=(1-percent_of0_data)*len(unseuc_dataset)
#print(percent_of0_data*len(unseuc_dataset))
x_train_0=unseuc_dataset[:int(percent_of0_data*len(unseuc_dataset))]
x_train_1=succ_dataset[:int((percent_of0_data)*len(succ_dataset))]
x_train=pd.concat([x_train_0,x_train_1])
#print(x_train.shape)
x_test_0=unseuc_dataset[int(percent_of0_data*len(unseuc_dataset)):]
x_test_1=succ_dataset[int((percent_of0_data)*len(succ_dataset)):]
x_test=pd.concat([x_test_0,x_test_1])
#print(x_test.shape)
print(x_train.shape,x_test.shape)

(99080, 98) (8456, 98)

In [17]:
from sklearn.utils import shuffle
x_train=shuffle(x_train)
x_test=shuffle(x_test)

In [18]:
y_train=x_train['label']
y_train.head()

46643    0
88321    0
42261    0
91326    0
19149    0
Name: label, dtype: int64

In [19]:
y_test=x_test['label']
y_test.head()

100966    0
103618    0
100165    0
106654    0
96862     1
Name: label, dtype: int64

In [20]:
x_train=x_train.drop(columns=['label'])
x_test=x_test.drop(columns=['label'])

In [21]:
x_train.head()

,no_of_founders,no_of_funding_rounds,no_of_board_members,amount_raised,age_months,no_of_investors,social_media_presence,employee_count_1-10,employee_count_10000+,employee_count_1001-5000,...,last_funding_status_series_b,last_funding_status_series_c,last_funding_status_series_d,last_funding_status_series_e,last_funding_status_series_f,last_funding_status_series_g,last_funding_status_series_h,last_funding_status_series_i,last_funding_status_series_unknown,last_funding_status_undisclosed
46643,1,0,0,0.0,76,0,1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88321,0,0,0,0.0,100,0,1.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
42261,1,0,0,0.0,64,0,1.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
91326,1,0,0,0.0,51,0,1.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
19149,2,2,0,245000.0,67,3,1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, auc, confusion_matrix, classification_report,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.model_selection import KFold
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn import preprocessing, metrics
#from xgboost import XGBClassifier
#warnings.filterwarnings('ignore')

In [23]:
clfs = {
#'LogisticRegression' : LogisticRegression(),
#'GaussianNB': GaussianNB(),
'RandomForest': RandomForestClassifier(),
'DecisionTreeClassifier': DecisionTreeClassifier(),
#'SVM': SVC(),
'KNeighborsClassifier': KNeighborsClassifier(),
'GradientBoosting': GradientBoostingClassifier(),
}

In [24]:
models_report = pd.DataFrame(columns = ['Model', 'Precision_score', 'Recall_score','F1_score', 'Accuracy'])

for clf, clf_name in zip(clfs.values(), clfs.keys()):
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    y_score = clf.score(x_test,y_test)
    
    #print('Calculating {}'.format(clf_name))
    t = pd.Series({ 
                     'Model': clf_name,
                     'Precision_score': metrics.precision_score(y_test, y_pred),
                     'Recall_score': metrics.recall_score(y_test, y_pred),
                     'F1_score': metrics.f1_score(y_test, y_pred),
                     'Accuracy': metrics.accuracy_score(y_test, y_pred)}
                   )

    models_report = models_report.append(t, ignore_index = True)

models_report

/home/rk/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

                    Model  Precision_score  Recall_score  F1_score  Accuracy
0            RandomForest         0.277551      0.102256  0.149451  0.908467
1  DecisionTreeClassifier         0.224852      0.114286  0.151545  0.899361
2    KNeighborsClassifier         0.368421      0.052632  0.092105  0.918401
3        GradientBoosting         0.333333      0.003008  0.005961  0.921121