In [1]:
import pandas as pd

In [2]:
organisations = pd.read_csv("/home/rk/raj_data_cb/organizations.csv")

/home/rk/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

organisations.head(2)

In [3]:
organisations.shape

(756475, 35)

In [4]:
len(organisations['company_name'].unique())

744780

## Find unique categories

In [5]:
organisations['category_group_list'][:2]

0    Biotechnology,Data and Analytics,Design,Health...
1              Apps,Mobile,Software,Travel and Tourism
Name: category_group_list, dtype: object

In [6]:
category_group_list = organisations['category_group_list'].tolist()

In [7]:
category_group_list = [str(l) for l in category_group_list]

In [8]:
category_group_list = [l.split(',') for l in category_group_list]

In [9]:
category_group_list = [item for sublist in category_group_list for item in sublist]

In [10]:
category_group_list = list(set(category_group_list))

In [11]:
cat_group = pd.DataFrame()

In [12]:
cat_group['category_groups'] = category_group_list

In [13]:
cat_group.to_excel('category_group.xlsx',index=False)

In [14]:
cats = organisations['category_list'].tolist()
cats = [str(l) for l in cats]
cats = [l.split(',') for l in cats]
cats = [item for sublist in cats for item in sublist]
cats = list(set(cats))
cat_list_df = pd.DataFrame()
cat_list_df['category_list'] = cats
cat_list_df.to_excel('category_list.xlsx',index=False)

In [15]:
cat_list_df.shape

(743, 1)

## Get Year

In [16]:
def get_year(x):
    if x!='':
        return x.split('-')[0]
    else:
        return '0'

In [17]:
organisations['founded_on'].tolist()[:5]

[nan, '2015-01-01', '1968-07-18', '1968-01-01', '1955-01-01']

In [18]:
organisations['founded_on'] = organisations['founded_on'].fillna('')

In [19]:
organisations['founded_year'] = organisations['founded_on'].apply(lambda x:get_year(x))

In [20]:
organisations['founded_year'] = organisations['founded_year'].apply(lambda x:int(x))

In [21]:
organisations = organisations.loc[organisations['founded_year']>=2008]

In [22]:
organisations = organisations.loc[organisations['country_code']=='USA']

In [23]:
organisations['employee_count'].unique()

array(['1-10', '10000+', '251-500', '11-50', '1001-5000', '501-1000',
       'unknown', '51-100', '101-250', '5001-10000'], dtype=object)

In [24]:
organisations['Age'] = organisations['founded_year'].apply(lambda x:2019-x)

## Get No of Founders

In [25]:
jobs=pd.read_csv('/home/rk/raj_data_cb/jobs.csv')

In [26]:
jobs.columns

Index(['person_uuid', 'org_uuid', 'job_uuid', 'started_on', 'ended_on',
       'is_current', 'title', 'job_type'],
      dtype='object')

In [27]:
jobs.drop(columns=['job_uuid','started_on', 'ended_on','is_current','job_type','person_uuid'],inplace=True)
jobs.head()

,org_uuid,title
0,c75dfb95-7099-4597-be14-e31201c65b99,Vice President and Senior Project Manager
1,79609a18-e5ba-5be3-63e7-1fbbf6db8334,Senior Vice President
2,b9972c1b-4ce1-429f-a1de-de53c623597b,Board Member
3,ffcf22c1-82c8-c9a4-e509-d5b1001aea65,Quality Assurance Engineer
4,262e8313-49cc-4211-88d1-c41bb0d7bfcd,CEO

In [28]:
founders = jobs[jobs['title'].str.contains("Founder", na=False)]
founders.head()

                                org_uuid                    title
6   82c41906-0d75-a25a-602d-92bd6eb77e44       Co-Founder and CEO
21  011d0f2f-a39b-e667-d270-35c30dac9d47               Co-Founder
22  0da785ca-43a3-bf10-435d-82d9a5ec031a  Co-Founder and CFO, COO
24  2ebc532d-a93f-98b1-7e0d-0dd20d992b4b       Co-Founder and CEO
35  881c8903-5bd2-a3bd-ef26-f318439e848c       Co-Founder and CPO

In [29]:
founders.columns
founders.shape

(223129, 2)

In [30]:
tmp=founders

In [31]:
organisations.shape

(108474, 37)

In [32]:
tmp1=tmp.groupby(['org_uuid']).size().reset_index(name='no_of_founders')
tmp1.head(2)

                               org_uuid  no_of_founders
0  00002470-bff7-6226-5800-0ca1b3787b6f               1
1  00007c5c-9260-0dfb-c160-89a416f1a7cc               1

In [33]:
merged_orgs=pd.merge(organisations,tmp1, left_on=['uuid'], right_on=['org_uuid'], how='left')
merged_orgs.head(2)

,Unnamed: 0,company_name,roles,permalink,domain,homepage_url,country_code,state_code,region,city,...,uuid,created_at,updated_at,primary_role,type,description,founded_year,Age,org_uuid,no_of_founders
0,1,Grown Ocean,company,/organization/grown-ocean,grownocean.com,http://www.grownocean.com,USA,NY,New York City,New York,...,eea6f58a-b728-d416-7e38-6ca5bad23e2d,2016-04-26 20:25:23,2019-03-25 20:00:23,company,organization,Grown Ocean is the mobile app for planning you...,2015,4,NaN,NaN
1,672,Adaptive Media,company,/organization/adaptive-media-3,adaptivemedia.com,http://www.adaptivemedia.com/,USA,CA,SF Bay Area,Sunnyvale,...,c12db09a-ae82-d698-2053-7b50f669ba74,2015-11-29 12:31:59,2018-02-12 23:58:48,company,organization,Adaptive Media is an audience and content mone...,2012,7,NaN,NaN

In [34]:
merged_orgs.fillna(0)

,Unnamed: 0,company_name,roles,permalink,domain,homepage_url,country_code,state_code,region,city,...,uuid,created_at,updated_at,primary_role,type,description,founded_year,Age,org_uuid,no_of_founders
0,1,Grown Ocean,company,/organization/grown-ocean,grownocean.com,http://www.grownocean.com,USA,NY,New York City,New York,...,eea6f58a-b728-d416-7e38-6ca5bad23e2d,2016-04-26 20:25:23,2019-03-25 20:00:23,company,organization,Grown Ocean is the mobile app for planning you...,2015,4,0,0.0
1,672,Adaptive Media,company,/organization/adaptive-media-3,adaptivemedia.com,http://www.adaptivemedia.com/,USA,CA,SF Bay Area,Sunnyvale,...,c12db09a-ae82-d698-2053-7b50f669ba74,2015-11-29 12:31:59,2018-02-12 23:58:48,company,organization,Adaptive Media is an audience and content mone...,2012,7,0,0.0
2,852,Gazelle Lab,investor,/organization/gazelle-lab,gazellelab.com,http://gazellelab.com,USA,FL,Tampa,Tampa,...,409e006b-9731-94be-a389-e4f093f6aeb3,2011-08-23 23:53:19,2018-02-12 23:51:09,investor,organization,"Gazelle Lab is a TechStars Network member, men...",2011,8,409e006b-9731-94be-a389-e4f093f6aeb3,6.0
3,880,HealthAxis Group,company,/organization/healthaxis-com,healthaxis.com,http://www.healthaxis.com/,USA,FL,Tampa,Tampa,...,3246d054-f127-6c91-540d-0498f84a47fb,2015-11-30 13:44:57,2019-03-25 20:43:16,company,organization,The HealthAxis Group seeks to reboot healthcar...,2011,8,0,0.0
4,1065,Wokrr,company,/organization/wokrr,wokrr.com,https://wokrr.com,USA,CA,0,San Jose,...,90b1f841-706e-6b9e-cc1d-04adbd9f41a3,2015-09-22 18:58:31,2018-10-27 00:27:49,company,organization,"Wokrr is based in San Jose, California, United...",2016,3,90b1f841-706e-6b9e-cc1d-04adbd9f41a3,1.0
5,1585,iPolitics,company,/organization/ipolitics,ipolitics.com,http://www.ipolitics.com,USA,WA,0,Bellevue,...,7c4b3f94-20aa-0255-05da-7a76a4d667fb,2016-01-24 09:10:41,2018-10-26 22:38:32,company,organization,iPolitics.com is the premier political communi...,2010,9,0,0.0
6,2010,iAnalyst,company,/organization/ianalyst,ianalyst.com,https://ianalyst.com/,USA,FL,Miami,Miami,...,f3ba7040-5950-a161-0e35-c94f444c6911,2016-03-14 09:40:14,2019-04-01 17:14:30,company,organization,A full service agency specializing in Internet...,2009,10,0,0.0
7,2277,SkyFish.Com,company,/organization/skyfish-com,skyfish.com,http://www.skyfish.com/,USA,CT,Hartford,New Haven,...,f13aad2a-082e-2286-72c7-2664a10685c0,2016-03-17 08:26:07,2019-03-25 19:19:24,company,organization,Skyfish.com provides the airline and aerospace...,2011,8,0,0.0
8,2319,HomeCaravan.com,company,/organization/homecaravan-com,homecaravan.com,http://www.homecaravan.com,USA,CA,Los Angeles,Pasadena,...,fc892182-248a-7737-e1a6-513edd990dc3,2016-03-18 06:32:52,2019-03-25 19:43:39,company,organization,0,2014,5,0,0.0
9,2397,EverPoint,company,/organization/everpoint,everpoint.com,http://www.everpoint.com,USA,FL,0,Boca Raton,...,52b4ec5c-1baa-1ef5-3f4c-fbbff68b35c2,2016-03-19 04:35:01,2018-04-17 17:10:24,company,organization,0,2014,5,0,0.0
10,2569,gForce,company,/organization/gforce-2,gforcesystems.com,http://www.gforcesystems.com,USA,CA,0,San Jose,...,69d0dd9d-15e7-d64a-452c-fb6942b6d69c,2016-03-19 09:42:08,2019-03-25 20:48:03,company,organization,0,2009,10,0,0.0
11,2628,Thirsty,company,/organization/thrsti,thirsty.com,http://thirsty.com,USA,CA,SF Bay Area,Palo Alto,...,9f75b96c-1f30-bb84-0851-f82f6854e43c,2011-02-11 12:43:36,2018-02-12 23:59:54,company,organization,Thirsty is a marketplace for advertising campa...,2010,9,0,0.0
12,2920,"Liberate Ideas, Inc","company,investor",/organization/liberate-technologies,liberate.com,http://www.liberate.com/,USA,NJ,Newark,Montclair,...,cefd0ba1-94f8-fc03-9b57-f61dd6c12038,2011-07-26 07:36:56,2018-10-26 22:40:53,company,organization,Liberate Ideas Inc® is a leading mobile health...,2013,6,0,0.0
13,3052,M-Commerce Ventures,"company,investor",/organization/m-commerce-ventures,0,0,USA,CA,0,San Francisco,...,f4ea1b0c-d532-d2dc-43d4-f9b5701ceef1,2016-04-05 04:13:21,2018-05-14 08:59:37,investor,organization,0,2012,7,0,0.0
14,3246,TestU,company,/organization/testu,testu.com,http://www.testu.com/,USA,NY,0,New York,...,7a9b369f-336f-325b-e74f-c5c912c135e7,2016-11-21 10:36:10,2018-10-27 00:11:22,company,organization,0,2016,3,7a9b369f-336f-325b-e74f-c5c912c135e7,1.0
15,3320,Gray Scale Technologies,company,/organization/gray-scale-technologies,techgrayscale.com,http://techgrayscale.com,USA,CO,Denver,Denver,...,17f347e8-5519-6a79-81ae-0c5fd37c689f,2015-12-22 11:41:00,2019-03-25 19:53:21,company,organization,0,2008,11,0,0.0
16,3751,Zassi Medical Evolutions,company,/organization/zassi-medical-evolutions,zassimedical.com,http://www.zassimedical.com,USA,FL,Jacksonville,Fernandina Beach,...,b58b3ce3-733f-8c85-1436-68a0f6f4b7b6,2015-08-03 12:06:09,2019-01-23 21:23:53,company,organization,0,2008,11,0,0.0
17,3845,Purple Drop,company,/organization/purple-drop,purpledrop.in,http://www.purpledrop.in/,USA,CA,SF Bay Area,San Francisco,...,8d95e2de-d0a5-b3f0-686b-94109acddce2,2016-09-30 09:50:39,2019-03-25 19:48:23,company,organization,Purple Drop is a one-stop design studio which ...,2010,9,0,0.0
18,4691,iPower Technologies,company,/organization/ipower-technologies,goipower.com,http://www.goipower.com/,USA,FL,Palm Beaches,Boca Raton,...,27af04fb-5420-9c3f-1d35-fa3f10c7ceb9,2015-08-09 11:00:06,2019-04-02 00:51:35,company,organization,iPower Technologies is a comprehensive technol...,2009,10,0,0.0
19,4725,TekConnect Corporation,company,/organization/tekconnect-corporation,tekconnect.ca,https://tekconnect.ca/,USA,NJ,Philadelphia,Cherry Hill,...,203b2494-536d-b68f-7bd8-b195c715f8c0,2015-08-09 06:26:38,2019-03-25 19:18:11,company,organization,TekConnect provides information technology ser...,2010,9,0,0.0
20,5227,Fandango,company,/organization/fandango,fandango.com,http://www.fandango.com,USA,CA,Los Angeles,Los Angeles,...,13b17879-808e-8ba0-c2c9-f1da2c4ba882,2008-06-25 03:09:17,2019-04-01 23:49:09,company,organization,Fandango is a moviegoer destination and a unit...,2012,7,13b17879-808e-8ba0-c2c9-f1da2c4ba882,2.0
21,5252,Clever Automation,company,/organization/clever-automation,cleverautomation.com,https://cleverautomation.com,USA,TX,0,Odessa,...,6d891db2-3fe6-c1c7-6b36-adeaae206928,2017-02-20 10:05:22,2019-03-25 19:38:48,company,organization,0,2012,7,0,0.0
22,5637,Ollie's Holdings,company,/organization/ollie-s-holdings,0,0,USA,PA,Harrisburg,Harrisburg,...,3d7da77f-4a9c-bf03-f5c4-303a86f7c2eb,2017-05-22 12:14:41,2018-02-12 23:50:34,company,organization,"Ollie's Holdings, Inc. operates retail stores.",2012,7,0,0.0
23,5699,HB Home Bistro,company,/organization/hb-home-bistro,homebistrochicago.com,http://homebistrochicago.com,USA,IL,0,Chicago,...,a80465da-3faf-0748-9542-fb9bcd4bcc12,2014-12-20 13:58:55,2019-03-25 20:00:06,company,organization,HB is a cozy storefront bistro nestled amidst ...,2008,11,0,0.0
24,6116,BUILT IMAGES,company,/organization/hometica,builtimages.com,http://www.builtimages.com/,USA,CA,Anaheim,San Clemente,...,04d8855a-1d87-db9c-7bbd-7caf0e27b392,2013-04-18 12:23:11,2018-10-26 22:44:59,company,organization,BUILT IMAGES stretches the imagination with Ri...,2012,7,0,0.0
25,6466,The Mobile 360,company,/organization/the-mobile-360,themobile360.com,https://themobile360.com/,USA,MO,0,Netherlands,...,cd2ac6f1-38cf-47e2-94d3-2c847c28687d,2018-10-24 16:15:48,2018-10-25 05:00:27,company,organization,The Mobile 360 is a well-read website portal t...,2016,3,cd2ac6f1-38cf-47e2-94d3-2c847c28687d,1.0
26,6672,iPlay,company,/organization/iplay,iplayamerica.com,http://www.iplayamerica.com,USA,NY,0,New York,...,4735d706-e763-d2f2-9993-3c6818102115,2011-01-06 13:30:44,2019-03-25 19:51:46,company,organization,0,2011,8,0,0.0
27,6919,Wink,company,/organization/wink,wink.com,http://Wink.com,USA,CA,0,Mountain View,...,231e0f6b-8bdf-28b0-a82c-b42bdec2c67d,2007-07-18 19:16:09,2018-10-27 00:31:28,company,organization,,2013,6,231e0f6b-8bdf-28b0-a82c-b42bdec2c67d,1.0
28,7346,TwentyFour6,company,/organization/twentyfour6,twentyfour6.com,http://www.twentyfour6.com,USA,IL,Chicago,Chicago,...,5a0d5df8-f9d5-49eb-00ed-5087f423eba0,2008-11-25 00:40:14,2019-04-24 13:54:14,company,organization,TwentyFour6 provides an LBA ad serving platfor...,2008,11,0,0.0
29,7592,Netstars,company,/organization/netstars,netstars.com,http://Netstars.com,USA,AZ,0,Phoenix,...,0046f141-eed7-4357-c79d-8c5881ae3731,2012-07-24 07:05:59,2018-02-12 23:49:53,company,organization,Netstars is a new startup that enables you to ...,2011,8,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108444,756218,ZVOO,company,/organization/zvoo,zvoo.com,http://zvoo.com/,USA,TX,Dallas,Dallas,...,7d477d98-e358-67ae-d512-6509b908e807,2017-08-31 11:29:11,2018-10-27 00:30:50,company,organization,ZVOO: Software Development Company offers affo...,2013,6,0,0.0
108445,756227,Zwapped,company,/organization/zwapped,zwapped.com,http://www.zwapped.com,USA,FL,Miami,Miami,...,8b3c69ff-5436-dc28-7bf3-15f2fa6321c6,2012-07-31 04:07:34,2018-10-27 00:30:51,company,organization,"buy, sell, swap and manage your daily deals",2011,8,0,0.0
108446,756230,zwear,company,/organization/zwear,zwear.org,http://zwear.org/,USA,CA,0,Sunnyvale,...,17b618dd-1509-18cc-5874-d9f9fc1a728e,2015-03-16 06:34:20,2019-03-25 20:01:01,company,organization,0,2014,5,0,0.0
108447,756249,Zwiffer,company,/organization/zwiffer,zwiffer.com,http://www.zwiffer.com,USA,IL,0,Chicago,...,a36aa6e6-6082-1546-7cfa-cfe4c14df9fc,2013-10-29 22:17:01,2019-03-25 19:16:02,company,organization,Zwiffer builds native iOS Applications. Think...,2010,9,0,0.0
108448,756250,ZwiftPay,company,/organization/zwift-pay,zwiftpay.com,http://www.zwiftpay.com/,USA,MA,0,Boston,...,e2b1b1d7-12d1-b4cc-5324-70be89947e47,2016-01-13 13:28:24,2018-10-27 00:30:52,company,organization,0,2015,4,e2b1b1d7-12d1-b4cc-5324-70be89947e47,1.0
108449,756252,Zwikk,company,/organization/zwikk,zwikk.com,http://zwikk.com,USA,NY,New York City,Bronx,...,087edaf4-30a2-6eb7-243a-9445ef2e30f7,2013-01-28 23:53:48,2018-10-27 00:30:52,company,organization,"Buy and sell textbooks, study guides, clothing...",2012,7,087edaf4-30a2-6eb7-243a-9445ef2e30f7,1.0
108450,756254,ZwillGen PLLC,company,/organization/zwillgen-pllc,zwillgen.com,http://zwillgen.com/,USA,DC,"Washington, D.C.",Washington,...,e22bb24f-ba1c-3b58-eb79-65f1460473e9,2014-09-19 12:35:35,2019-03-25 18:47:04,company,organization,ZwillGen PLLC is a boutique law firm that has ...,2010,9,0,0.0
108451,756261,ZwitterCo,company,/organization/zwitterco,zwitterco.com,https://www.zwitterco.com/,USA,MA,Boston,Cambridge,...,1fc22ae9-3488-448c-8258-2b19cc58516a,2018-09-17 05:31:34,2018-09-17 05:32:52,company,organization,0,2018,1,0,0.0
108452,756279,ZX Ventures,investor,/organization/zx-ventures,zx-ventures.com,http://zx-ventures.com/,USA,NY,New York City,New York,...,24e99718-5746-1166-c6cf-e6d937c42452,2016-04-20 17:18:13,2018-07-02 15:44:06,investor,organization,ZX Ventures is brewing up the future. ZX Ventu...,2016,3,24e99718-5746-1166-c6cf-e6d937c42452,2.0
108453,756286,Zybek Sports,company,/organization/zybek-sports,zybeksports.com,https://www.zybeksports.com/,USA,CO,Denver,Broomfield,...,6f3619ad-d622-4610-9b25-75b32bb8b2ca,2018-03-05 06:51:50,2018-05-04 06:16:39,company,organization,"Zybek Sports was founded in Boulder, Colorado ...",2008,11,0,0.0
108454,756293,Zycamore,company,/organization/morereporting,zycamore.com,http://www.zycamore.com,USA,UT,Salt Lake City,Provo,...,75ba195c-cebc-e0db-5b0f-ecfeaeb894ad,2015-02-02 03:40:11,2019-03-25 19:31:35,company,organization,0,2014,5,0,0.0
108455,756295,ZYCI CNC Machining,company,/organization/zyci-cnc-machining,zyci.com,http://www.ZYCI.com,USA,GA,Atlanta,Atlanta,...,1d7307b4-3c47-8ace-3629-6116ee56add6,2016-01-24 19:42:16,2019-03-25 18:53:32,company,organization,We make parts from your 3D models by CNC machi...,2013,6,1d7307b4-3c47-8ace-3629-6116ee56add6,1.0
108456,756304,Zydness Inc.,company,/organization/zydness-inc,zydness.com,http://www.zydness.com,USA,CA,SF Bay Area,San Francisco,...,9c73f374-dd47-441f-9374-7a4bd7379eec,2017-12-05 06:16:57,2019-03-25 19:57:53,company,organization,"Aggregation of the best classes in Zumba, Yoga...",2015,4,0,0.0
108457,756306,ZYE Technologies,company,/organization/zye-technologies,zyetechnologies.com,http://www.zyetechnologies.com,USA,IL,Chicago,Hoffman Estates,...,fc42d7c9-31f9-631f-1a7d-c8f7fbd978f1,2015-06-23 21:32:57,2019-03-25 19:33:45,company,organization,ZYE technologies is an independent third party...,2011,8,0,0.0
108458,756314,Zygood,company,/organization/zygood,0,0,USA,MD,MD - Other,Dayton,...,6807d5d4-a9d1-45d0-858c-69473fd998fd,2018-10-04 14:12:42,2018-10-04 14:12:42,company,organization,Zygood is a developer and marketer of medical ...,2014,5,0,0.0
108459,756321,Zygus Capital,investor,/organization/zygus-capital,zygus.com,https://www.zygus.com/,USA,NY,New York City,New York,...,9eb7f207-cfdc-4c7d-a6d8-e6ffbc63e8d8,2019-02-22 04:51:46,2019-04-01 23:17:21,investor,organization,Zygus Capital is a partner-owned investment fi...,2018,1,0,0.0
108460,756338,Zymbit,company,/organization/zymbit,zymbit.com,https://www.zymbit.com,USA,CA,Santa Barbara,Santa Barbara,...,6ffeb09f-e4a1-40b7-b075-80982afde4af,2018-09-05 06:02:48,2019-03-30 00:48:14,company,organization,At Zymbit they work with IoT developers and OE...,2014,5,6ffeb09f-e4a1-40b7-b075-80982afde4af,2.0
108461,756351,Zymolo Inc.,company,/organization/zymolo-inc,zymolo.com,https://www.zymolo.com/,USA,CA,San Diego,San Diego,...,4ca8b54c-7192-3753-a99f-758d873796b3,2017-06-19 02:43:29,2018-02-12 23:21:13,company,organization,0,2016,3,0,0.0
108462,756363,Zync Render,company,/organization/zync-render,zyncrender.com,https://www.zyncrender.com/,USA,MA,0,Boston,...,af76c4af-c26a-508b-9841-a050ba284cc6,2014-08-26 17:15:20,2018-10-27 00:31:00,company,organization,ZYNC is the visual effects industry’s first co...,2010,9,0,0.0
108463,756368,Zyng Advertising Networks,company,/organization/zyng-advertising-networks,digitalholdingsinc.com,https://digitalholdingsinc.com/,USA,MD,Baltimore,Glen Burnie,...,904d1d3d-1019-403a-bd07-490b9a88bda1,2019-03-28 04:07:32,2019-03-28 04:08:03,company,organization,Developer of a proprietary software. The compa...,2010,9,0,0.0
108464,756370,Zynga.org,company,/organization/zynga-org,zynga.org,http://zynga.org/,USA,CA,0,San Francisco,...,f3ed2cad-aeac-ede3-650e-e86d228bc4c0,2014-12-21 17:02:25,2019-04-01 17:17:16,company,organization,"Zynga develops, markets, and operates online s...",2009,10,0,0.0
108465,756374,ZYNK.,company,/organization/marketing-your-app,marketingyourapp.com,http://www.marketingyourapp.com,USA,MA,Boston,Cambridge,...,e4d6667f-0738-afa8-7ebe-dd1f0cab188c,2010-12-14 22:00:31,2019-03-25 19:50:41,company,organization,Marketing Your App is a mobile app marketing a...,2016,3,0,0.0
108466,756378,Zynsoft,company,/organization/zynsoft,zynsoft.com,http://zynsoft.com,USA,CA,0,Pleasanton,...,a99447ce-7108-c186-0dd8-8803a8901fa8,2012-08-28 23:03:07,2019-03-25 20:33:40,company,organization,This company focus on useful apps for daily li...,2011,8,0,0.0
108467,756384,ZypPages,company,/organization/zyppages,zyppages.com,http://zyppages.com,USA,CA,SF Bay Area,Palo Alto,...,c081d375-ba30-a1a3-18e4-830a3e050755,2014-02-13 16:57:54,2019-03-25 19:14:00,company,organization,ZypPages is the world’s simplest internet post...,2011,8,c081d375-ba30-a1a3-18e4-830a3e050755,2.0
108468,756388,Zyprr,company,/organization/zyprr,zyprr.com,https://www.zyprr.com,USA,MA,Boston,Chelsea,...,e6b6dff9-2469-d9bc-744f-6b799d12d28d,2015-07-09 21:43:38,2019-03-25 19:56:33,company,organization,Zyprr is a highly customizable mid-market busi...,2014,5,0,0.0
108469,756397,Zyrion Inc,company,/organization/zyrion,zyrion.com,http://www.zyrion.com,USA,CA,SF Bay Area,Sunnyvale,...,dac5dca2-7581-0382-e57e-a7ec9d69bc05,2010-07-07 11:51:29,2018-02-12 23:28:04,company,organization,Zyrion is a network monitoring software compan...,2008,11,dac5dca2-7581-0382-e57e-a7ec9d69bc05,1.0
108470,756399,Zyrobotics,company,/organization/zyrobotics,zyrobotics.com,http://zyrobotics.com/,USA,GA,Atlanta,Atlanta,...,adb7a3e2-e120-345c-2a6b-385cb117d343,2015-06-04 04:16:04,2019-03-25 20:48:09,company,organization,"Zyrobotics, LLC is an assistive technology com...",2012,7,adb7a3e2-e120-345c-2a6b-385cb117d343,2.0
108471,756428,ZZAlpha,company,/organization/zzalpha,zzalpha.com,http://www.zzalpha.com,USA,AZ,Tucson,Tucson,...,a93a5aed-b456-7f55-7cbb-0aa4b22720d1,2011-09-17 02:03:33,2019-03-25 20:01:06,company,organization,ZZAlpha LTD provides daily recommendations of ...,2010,9,a93a5aed-b456-7f55-7cbb-0aa4b22720d1,1.0
108472,756438,ZZoom Media,company,/organization/zzoom-media,zzoomedia.om,http://www.zzoomedia.om,USA,WA,Seattle,Vancouver,...,f6e4ff32-0887-419e-42ef-82512c072e4f,2011-01-21 03:39:26,2019-03-25 20:30:06,company,organization,ZZoom Media is comprised of individuals with a...,2010,9,0,0.0
108473,756462,ΛDΛPTRΛCK,company,/organization/adaptrack,0,0,USA,IL,Chicago,Chicago,...,d4855681-0960-48a8-a054-2f76d2bf0e6f,2018-09-06 21:42:25,2019-04-01 23:48:33,company,organization,0,2018,1,0,0.0

In [35]:
len(merged_orgs['company_name'].unique())

107536

In [36]:
organisations=merged_orgs
organisations.shape

(108474, 39)

In [37]:
organisations=organisations.drop_duplicates(subset=['company_name'])

In [38]:
organisations.shape

(107536, 39)

## Get Board Members And Advisors

In [39]:
people = pd.read_csv("/home/rk/raj_data_cb/people.csv")

In [40]:
board_members = people[people['primary_affiliation_title'].str.contains("Board Member") | people['primary_affiliation_title'].str.contains("Advisor") ]

In [41]:
from collections import Counter
board_orgs = board_members['primary_affiliation_organization'].tolist()
count_board_members = Counter(board_orgs)

In [42]:
def get_board_count(org):
    try:
        return count_board_members[org]
    except:
        return 0

In [43]:
organisations['no_of_board_members'] = organisations['company_name'].apply(lambda x:get_board_count(x))

/home/rk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

## Get Location

In [44]:
def get_location(state_code):
    
    statename_mappng={'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona',
                      'AR': 'Arkansas', 'CA': 'California', 'CO': 'Colorado', 
                      'CT': 'Connecticut', 'DE': 'Delaware', 'FL': 'Florida', 
                      'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho', 
                      'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 
                      'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana', 
                      'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts', 
                      'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi', 
                      'MO': 'Missouri', 'MT': 'Montana', 'NE': 'Nebraska', 
                      'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey', 
                      'NM': 'New Mexico', 'NY': 'New York', 'NC': 'North Carolina', 
                      'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma', 
                      'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 
                      'SC': 'South Carolina', 'SD': 'South Dakota', 'TN': 'Tennessee', 
                      'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont', 'VA': 'Virginia', 
                      'WA': 'Washington', 'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming','DC':'DC','AE':'AE'}
    NE=['Maine', 'Massachusetts', 'Rhode Island', 'Connecticut', 'New Hampshire', 'Vermont', 
        'New York', 'Pennsylvania', 'New Jersey', 'Delaware', 'Maryland']
    SE=['West Virginia', 'Virginia', 'Kentucky', 'Tennessee', 'North Carolina', 'South Carolina', 'Georgia, Alabama', 
        'Mississippi', 'Arkansas', 'Louisiana', 'Florida']
    MW=['Ohio', 'Indiana', 'Michigan', 'Illinois', 'Missouri', 'Wisconsin', 'Minnesota', 'Iowa', 'Kansas', 'Nebraska', 'South Dakota', 
       'North Dakota'] 
    SW=['Texas', 'Oklahoma', 'New Mexico', 'Arizona']
    W=['Colorado', 'Wyoming', 'Montana', 'Idaho', 'Washington', 'Oregon', 'Utah', 'Nevada', 'California','Alaska', 'Hawaii','DC']
    
    if statename_mappng[state_code] in NE:
        return 'northeast'
    elif statename_mappng[state_code] in SE:
        return 'southeast'
    elif statename_mappng[state_code] in MW:
        return 'midwest'
    elif statename_mappng[state_code] in SW:
        return 'southwest'
    elif statename_mappng[state_code] in W:
        return 'west'
    else:
        return 'others'

In [45]:
organisations['location'] = organisations['state_code'].apply(lambda x:get_location(x))

/home/rk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [46]:
organisations.columns

Index(['Unnamed: 0', 'company_name', 'roles', 'permalink', 'domain',
       'homepage_url', 'country_code', 'state_code', 'region', 'city',
       'address', 'status', 'short_description', 'category_list',
       'category_group_list', 'funding_rounds', 'funding_total_usd',
       'founded_on', 'last_funding_on', 'closed_on', 'employee_count', 'email',
       'phone', 'facebook_url', 'linkedin_url', 'cb_url', 'logo_url',
       'twitter_url', 'aliases', 'uuid', 'created_at', 'updated_at',
       'primary_role', 'type', 'description', 'founded_year', 'Age',
       'org_uuid', 'no_of_founders', 'no_of_board_members', 'location'],
      dtype='object')

In [47]:
orgs1 = organisations[['company_name','employee_count','Age','location','no_of_founders','no_of_board_members','description','state_code','country_code','status','category_group_list','founded_on']]

 Checkpoint save

In [48]:
orgs1.to_csv('org_data.csv',index=False)

In [49]:
orgs1 = pd.read_csv('org_data.csv')

## No of Funding Rounds and Amount Raised

In [50]:
funds = pd.read_csv('/home/rk/raj_data_cb/funding_rounds.csv')

In [51]:
funding_orgs = funds['company_name'].tolist()
count_funding_rounds = Counter(funding_orgs)

In [52]:
orgs1['no_of_funding_rounds'] = orgs1['company_name'].apply(lambda x:count_funding_rounds[x])

In [53]:
count_funding_rounds

Counter({'OnPath Technologies': 4,
         'Distributed ID': 3,
         'Snaptrude': 2,
         'Vapor Corp': 1,
         'CloudVelox': 3,
         'HaloSource': 4,
         'Lucid Group Communications': 1,
         'Create! Art Collective': 1,
         'Sharestates': 3,
         'Bean Biltmore Pointe': 1,
         'SquareOne': 6,
         'Digital Influencers': 3,
         'Datacorp': 1,
         'Perspectico': 2,
         'Carbon Robotics': 6,
         '7LeKang (7lk)': 4,
         'Delcath Systems': 4,
         'Factual': 4,
         'Energy Automation System': 1,
         'Tandem Diabetes Care': 8,
         'Epavlis SA': 1,
         'mValent': 4,
         'Baby2Body': 5,
         'The University of Chicago Medicine': 3,
         'Expway': 6,
         'Satin Creditcare Network Limited (SCNL)': 7,
         'CHF Solutions, Inc.': 11,
         'Dotpay': 1,
         'Intelligent Mobile Support': 3,
         'Safe Communications': 6,
         'Medley': 1,
         'eCommLink': 1,
         'Dublway - daily commute ridesharing': 2,
         'Protagoras': 1,
         'Graylog': 3,
         '1Lay': 2,
         'Integral Ad Science': 7,
         'MomentCam': 1,
         'Trendsetters': 3,
         'FlowCommand': 2,
         'See-R': 1,
         'Shelvspace': 5,
         'OpenHatch': 1,
         'Healthenablr': 1,
         'Swirl Networks': 3,
         'NERv Technology Inc.': 14,
         'Quantac': 2,
         'BuzzStarter': 4,
         'Galley': 2,
         'E-Cloud (云一传媒)': 1,
         'New West Genetics': 2,
         'New York Medical College': 1,
         'Black Arrow': 1,
         'TripMark': 2,
         'disruptient': 1,
         'Fusion Connect': 6,
         '500 Startups': 6,
         'DesignMySoap.com': 2,
         'Picsel Technologies': 3,
         'Acopia Networks': 5,
         'Digi.Bio': 1,
         'BrightFunnel': 4,
         'Exegy': 3,
         'Photonics Industries': 2,
         'Threatcare': 5,
         'Vermando': 2,
         'Razorfish Technologies India': 1,
         'CarPlanner': 2,
         'HeyHub': 3,
         'Space Oddity Films': 1,
         'AgenDx Biosciences': 3,
         'Ro': 4,
         'Scientific Revenue': 2,
         'Eden GeoPower': 10,
         'Viroblock': 3,
         'Aqualligence': 2,
         'SwarmSales, Inc.': 2,
         'Handle': 9,
         'Venturepax': 4,
         'Secpanel': 1,
         'Ascension Ventures Limited': 1,
         'Farfetch': 8,
         'Reflectent Software': 2,
         'NJOY': 5,
         'Gymbox': 4,
         'Infinite Mixed Reality': 1,
         'DrinkSavvy': 1,
         'Power Mech Projects': 1,
         'Numan': 1,
         'Sprout': 9,
         'MabVax Therapeutics': 13,
         'CoWare': 6,
         'Validea': 1,
         'TradeOut.com': 2,
         'Soothe': 5,
         'Twin Lakes Mall': 1,
         'IRIS Advanced Engineering': 1,
         'Ushahidi': 7,
         'Hortonworks': 5,
         'SenseTime': 7,
         'GPiO': 1,
         'PatSnap': 5,
         'Lucky Oyster': 3,
         'slicedbread': 1,
         'TPx Communications': 5,
         'Wizenoze': 1,
         'Meqon Research': 1,
         'Wisran': 2,
         'Space.com': 2,
         'Legal Diction': 2,
         'First To File': 4,
         'Markado': 2,
         'thingdust': 1,
         "L'appartement Ticolas": 4,
         'Sunfinity Solar': 1,
         'MedLink': 1,
         '1st Dental Laboratories': 1,
         'Flexbooth': 3,
         'Wanchain': 3,
         'Riim': 2,
         'AxisMobile': 1,
         'Roniin': 2,
         "Caleb's Cooking Co.": 1,
         'SPT Offshore': 1,
         'Omniscience Corporation': 5,
         'FretLink': 3,
         'Lundalogik': 1,
         'ModuleQ': 4,
         'Cogenta Systems': 9,
         'SonicLiving': 1,
         'MyBuys': 4,
         'BrainPlotting': 1,
         'Jiobit': 5,
         'In2cure': 1,
         'Wireless Technologies Center LLC': 1,
         'i-Optics': 3,
         'SpinGo': 5,
         'Mopp': 1,
         'Adwo Media Holdings': 2,
         'Click2Send': 1,
         'Senolytic Therapeutics': 1,
         'Xiaomi': 9,
         'Dolmen': 2,
         'Lumific': 4,
         'Domicilios.com': 4,
         'Prolifiq': 2,
         'Spyder Lynk': 4,
         'Noomeo': 3,
         'Social Games Herald': 1,
         'OmegaOn': 3,
         'Podo Labs': 10,
         'LineStream Technologies': 4,
         'Teranetics': 7,
         'Spotlight App': 1,
         'Cantex Pharmaceuticals': 6,
         'BB Park': 1,
         'STAFFME': 2,
         'Gynesonics': 13,
         'magnitude.asia': 1,
         '3DC.io': 2,
         'MedVet Medical & Cancer Centers for Pets': 7,
         'Virtualitics': 3,
         'ImaginAb': 4,
         'Infinity Box, Wufoo': 2,
         'Icebrg': 2,
         'Yibutrip': 1,
         'Life Perfusor Medical Technology (Laipu Medical)': 1,
         'Tera Funding': 2,
         'Digsy': 3,
         'Assembly': 10,
         'Endeca': 6,
         "She's Well": 3,
         'Melior Discovery': 9,
         'HuTerra': 7,
         'ibooks.com': 2,
         'Tagboard': 2,
         'Shippit': 6,
         'Lucideus': 5,
         'Rennovia': 5,
         'InterSymbol Communications': 2,
         'Udemy': 8,
         'New Zealand Whisky Collection': 1,
         'Marathon Technologies': 6,
         'Noknoker': 4,
         'Eblana Photonics': 2,
         'Antares Vision': 1,
         'Express Action': 1,
         'Ed4U': 1,
         'Magma Flooring': 3,
         'American Weapons Components': 1,
         'airPHX Environmental': 1,
         'YellowDog': 7,
         'Schooglink Private Limited': 1,
         'ApnaPaisa': 2,
         'Onconano Medicine': 3,
         'Xenoport': 5,
         'Otomagnetics': 3,
         'Adometry By Google': 5,
         'Cheyenne Mountain Games': 1,
         'AptamiR Therapeutics': 1,
         'Uhnder': 2,
         'Unveil': 1,
         'Aitek BV': 1,
         'Bromium': 5,
         'USINE IO': 2,
         'Infinity CCS': 1,
         'Flight Steward': 2,
         'RoboteX': 6,
         'Curiyo': 2,
         'Capigami': 1,
         'Everoad': 2,
         'Distrx': 1,
         'CNine Biosolutions': 1,
         'meQuilibrium': 5,
         'Quick Study Radiology': 6,
         'OPKIX': 4,
         'Antofenol': 2,
         'BlinkBio': 1,
         'Actions Semiconductor': 1,
         'Yakarouler': 1,
         'Envoy America': 5,
         'Epinions': 3,
         'Tricares': 3,
         'Ingresse': 6,
         'Uberflip': 3,
         'Horizon Fuel Cell Technologies': 2,
         'Quu Interactive': 1,
         'Partiac': 2,
         'Fyrno Inc.': 1,
         'amBX': 12,
         'MarbleShare': 1,
         'Nearthlab': 2,
         'Altar': 1,
         'Insightfil': 10,
         'Unchainedhouse.com': 1,
         'DOFREN': 2,
         'Zenstores': 4,
         'Bizdom': 1,
         'Nitero': 2,
         'Study Mentors': 1,
         'Dataram': 3,
         'One Core Intelligent': 1,
         'Socialpay': 1,
         'PJD Group': 1,
         'Stemgent': 9,
         'Red Points': 4,
         'VLP Therapeutics': 2,
         'MPawa': 1,
         "Chef'd": 2,
         'Inception Sciences': 3,
         'Skrilo': 1,
         'Inoviem Scientific': 3,
         'Engage Mobility': 1,
         'DiversyFund': 2,
         'Spartoo': 5,
         'Smart Monitor': 3,
         'LensAR': 11,
         'Metconnex': 1,
         'Laboratik': 4,
         'Mobiscope': 2,
         'Sagent Pharmaceuticals': 4,
         'Wefunder': 7,
         'Oishi Group': 1,
         'CyberX': 5,
         'Patch Gardens': 3,
         'Abroaders': 1,
         'Trakto.io': 5,
         'HTBASE': 1,
         'Acesion Pharma': 6,
         'Integrated BioTherapeutics': 1,
         'PlanetScale': 1,
         'Datacastle': 5,
         'Stream Tags': 1,
         'AdVolume': 1,
         'MaintenanceNet': 1,
         'Jiuxian': 8,
         'Kona Medical': 6,
         'Haimawan': 1,
         'Judys Book': 2,
         'Polystream': 3,
         'ExactTrak': 8,
         'N K Proteins': 1,
         'Expansive': 1,
         'adQuota': 1,
         'Edinburgh Molecular Imaging': 2,
         'Knowledge Adventure': 4,
         'Famous.co': 4,
         'Veriprise Wireless': 1,
         'Synappio': 3,
         'ManoMotion': 4,
         'Waygum, Inc.': 5,
         'Parcify': 4,
         'Hitsbook': 6,
         'Decooda': 1,
         'Linkdex': 7,
         'Canadian Non-Operated Resources Corp': 1,
         'SpaceTime Insight': 4,
         'Translimit': 2,
         'ProXcio': 1,
         'Linkingmed': 5,
         'Smartvue': 5,
         'PayPal': 5,
         'Startsub.com': 1,
         'Humanita': 1,
         'Progate': 1,
         'Major Sports Analysis': 2,
         'Jim Koala': 1,
         'Echo Consulting Group': 1,
         'Parachute8 Inc.': 2,
         'ZEDEDA': 2,
         'GO STAN': 1,
         'Jobr': 2,
         'Human Diagnosis Project': 1,
         'Trestle': 1,
         'Bravo Health': 1,
         'Ferroamp Elektronik': 2,
         'Crono, Inc.': 2,
         'X-Sten': 1,
         'ABL Farms': 1,
         'Life House': 3,
         'ZipLoan': 4,
         'Antix Labs': 2,
         'Greenvity Communications': 1,
         'Intuit': 3,
         'Rezzi': 1,
         'Spot.IM': 3,
         'Elite Education Media Group': 1,
         'Kandidate': 1,
         'Hotlist': 4,
         'Liva Healthcare': 4,
         'Erle Robotics': 2,
         'VIZI Healthcare': 1,
         'iTreatMD': 1,
         'Agora.io': 4,
         'Pilot Software, Inc.': 2,
         'TakeBus': 3,
         'Kegg': 2,
         '4G Capital': 1,
         'Thrive Global': 3,
         'Ving': 7,
         'Blaze Bioscience': 6,
         'Heartland Water Technology': 2,
         'Phonotonic': 1,
         'CloSys': 6,
         'FileHold Systems': 1,
         'uBeam': 5,
         'AgentPair': 4,
         'Encore Technologies': 6,
         'Zolertia': 3,
         'Arkadin': 2,
         'Eqinov': 1,
         'Aperto Networks': 15,
         'AQ BioMed': 1,
         'Kaiku Health': 4,
         'Neronote': 1,
         'Suntherm': 3,
         'LuckyToken': 1,
         'Education.com': 5,
         'Carwow': 6,
         'CATASYS': 15,
         'FundersClub': 1,
         'EarthWise Ferries Uganda Limited': 1,
         'EFW Swiss AG': 1,
         'AllSystem': 1,
         'Gamervision': 4,
         'Fiducioso Advisors': 4,
         'Acumen Pharmaceuticals': 2,
         'WedBrilliant': 1,
         'Zeals': 3,
         'Melinta': 11,
         'NiYO Solutions': 2,
         'Terafina': 1,
         'Radio NEXT': 1,
         'Mobile Satellite Ventures': 1,
         'Lumenz': 2,
         'Logical Clocks': 1,
         'AdEspresso': 3,
         'DTech Holdings': 1,
         'FirstLine': 1,
         'Invicta Networks': 1,
         'Zignal Labs': 5,
         'Edaris': 7,
         'Ardeo': 1,
         'Plug&Wear Srl': 2,
         'World Fuel': 1,
         'Tango Card': 7,
         'Kigo Kitchen': 2,
         'Zhihu': 6,
         'HandyLab': 6,
         'Ravenflow': 3,
         'Contratan.do': 1,
         'Globaleur': 2,
         'Super League Gaming': 6,
         'LOUPE': 1,
         'Deltek': 1,
         'Iven Medicare': 1,
         'DocASAP': 4,
         'Rover': 21,
         'ZBoard': 3,
         'Auxmoney': 4,
         'Protoqual Learning System': 1,
         'Ignitia': 3,
         'IPG': 4,
         'ToroMatcha': 1,
         'BioMedical Enterprises': 1,
         'Vioozer': 4,
         'Revivn': 2,
         'Progno Health': 1,
         'C3J Therapeutics': 4,
         'Youngevity International': 2,
         'Thalchemy': 2,
         'Tile': 4,
         'Deton': 5,
         'MODE': 4,
         'VALOREM': 2,
         'rethink': 1,
         'Ponte Solutions': 2,
         'ThirdChannel': 3,
         'Jellynote': 6,
         'Nujira': 6,
         'MSA Management': 3,
         'Mobility Services Hub MSH': 1,
         'Nova Property Investment Co. Ltd.': 2,
         'BreatheAmerica': 4,
         'Rive Technology': 5,
         'Try The World': 3,
         'JobHoreca': 1,
         'Point Broadband': 2,
         'Girly Stuff': 1,
         'Wellkeeper': 2,
         'SAN Valley Systems': 3,
         'Anju Software': 2,
         'Miura Systems': 2,
         'WOW Networks': 1,
         'Liechtenstein Life': 1,
         'Skip a Blink': 2,
         'SolFocus': 8,
         'Surface Therapeutics Ltd.': 2,
         'eBuddy': 3,
         'Heatworks': 8,
         'Loadcomplete': 2,
         'NanoRacks': 1,
         'GoGoGrandparent': 1,
         'Drop': 19,
         'Eco Products': 2,
         'Benivo (formerly FlatClub)': 5,
         'iSALON Beauty App': 1,
         'FLAG Therapeutics': 3,
         'GetO2': 14,
         'DEXMA': 6,
         'CostPocket': 2,
         'GamerDNA': 3,
         'VON Media Group': 1,
         'OWN.space': 1,
         'Leevia': 4,
         'Peloton Technology': 7,
         'Sxbbm': 2,
         'Service-Flow': 2,
         'Tine Health': 2,
         'By Rocket Box': 1,
         'Zeo': 7,
         'PastBook': 7,
         'cargonow': 1,
         'Eventure Interactive': 2,
         'Videntifier Technologies ehf': 2,
         'Woopie': 3,
         'SpaceX': 21,
         'Bizzuka': 1,
         'Yogome': 4,
         'Biotronics3D': 3,
         'Yummy77': 1,
         'Mininavident': 5,
         'Delivery Hero': 15,
         'Theranos': 10,
         'SmartCard Marketing Systems Inc. (SMKG:OTC)': 2,
         'xStudy SE': 1,
         'LED Optics': 1,
         'UsingMiles': 5,
         'Atlis': 3,
         'Hack Capital Ventures': 2,
         'Pixel Legend': 1,
         'Tima': 2,
         'Primoris Energy Solutions': 4,
         'Calient Technologies': 15,
         'Bactest': 4,
         'Sustain Natural': 1,
         'Ncrease': 1,
         'Snooper': 2,
         'Weibo': 2,
         'Corwave': 4,
         'Blume Distillation': 2,
         'Quantance': 7,
         'Idera Pharmaceuticals': 3,
         'Dorado.tech': 1,
         "H'DO ILOOK?": 1,
         'Tunnel International': 1,
         'Intezer': 2,
         'Mobile Interaction Company': 1,
         'NetDragon Education': 2,
         'Tokheim': 1,
         'Nyotron': 3,
         'Future Labs': 2,
         'Verso Learning': 1,
         'CellPly': 3,
         'Hive Tech': 1,
         'HumanCentric Performance': 1,
         'Kolibree': 3,
         'Michigan Opera Theatre': 1,
         'epacube': 5,
         'Venafi': 5,
         'CRM manager': 1,
         'ChemPass Kft': 2,
         'AccelGolf': 8,
         'Workface': 6,
         'TouchCare': 4,
         'YLG Salon': 2,
         'Jott': 3,
         'B-there.com': 2,
         'Edyza': 5,
         'Outbrain': 8,
         'Txt4': 2,
         'IRL Connect': 1,
         'Delfigo Security': 2,
         'Helloworld': 5,
         'RepRegen': 1,
         'PatternVision': 4,
         'Appdate-Me Ltd.': 2,
         'Suits Me': 1,
         'Muzy': 1,
         'SmartPrac': 1,
         'CrestaTech': 4,
         'Euveka': 1,
         'InXero': 2,
         'WoraPay': 4,
         'Zhonglan Media': 1,
         'Sunstone Communication Ltd': 1,
         'NuVuw.com': 1,
         'Mentr': 2,
         'Biaotianxia': 1,
         'Distrix': 1,
         'Homrun': 1,
         'Search Initiatives': 2,
         'SagaMedica': 9,
         'Felix Homes': 2,
         'Sizanani': 1,
         'FohBoh': 1,
         'Mediators Without Borders': 1,
         'Omni Bio Pharmaceutical': 5,
         'Coachademy': 3,
         'Blackdove': 2,
         'Joldit.com': 2,
         'PROFIFOX a.s.': 1,
         'SMART Business Advisory and Consulting': 1,
         'Lumenora': 1,
         'EyeGate Pharmaceuticals': 10,
         'Centerline Biomedical': 2,
         'Renovagen': 5,
         'Stride Health': 4,
         'RETC': 1,
         'Viss': 1,
         '9stacks': 2,
         'BlueStrata EHR': 3,
         'Loscam': 1,
         'MeetingPlay': 1,
         'Prospa': 5,
         'ArtSetters': 1,
         'MedStartr': 1,
         'Crumbs': 1,
         'Tour Raiser': 1,
         'Appcelerator': 9,
         'TrackActive': 3,
         'Yongqianbao': 5,
         'Of Course Learning': 2,
         'Malip': 1,
         'Brinkhof Group International': 1,
         'Mercury Puzzle': 1,
         'Juvo Labs': 1,
         'Mango Health': 4,
         'Full Spectrum Laser': 1,
         'Parvata Foods': 1,
         'LTN Global Communications': 2,
         'Fanzy': 4,
         'Auror': 3,
         'buyr.com': 2,
         'LANDBAY': 12,
         'Braavo': 1,
         'Plastic Logic Germany': 8,
         'Seedcamp': 5,
         'Bloom & Wild': 5,
         'TeleCIS Wireless': 2,
         'Problemcity.com': 1,
         'Tech.Li': 3,
         'Inspire': 5,
         'HUVRData': 2,
         'Shodogg': 5,
         'Todacell': 4,
         'Blackbuck': 6,
         'Create.io': 2,
         'Energy Recovery': 2,
         'Stateless': 4,
         'Zoomdata': 5,
         'Gridsum': 3,
         'ActiveCloud': 3,
         'Arcot Systems': 5,
         'Ingenium Golf': 3,
         'mything': 1,
         'SOAMAI': 2,
         'Repunch': 2,
         'Satellogic': 4,
         'ARIAD Pharmaceuticals': 6,
         'iDrip': 1,
         'Tarena': 4,
         'Flowerplus': 2,
         'Diodes Incorporated': 3,
         'Starent Networks': 5,
         'Line0': 3,
         'Switchboard Live': 3,
         'Encision': 2,
         'Job36': 1,
         'Imagine K12': 2,
         'Motiv': 6,
         'Yumist': 2,
         'Noto LMS': 1,
         'Ballista Securities': 1,
         'MKTxDatos Innovando Inteligencia Artificial SpA': 3,
         'Cognotion': 6,
         'Kadena': 3,
         'LifeShield': 6,
         'OneLogin': 7,
         'Airship': 9,
         'Kraydel': 3,
         'iMusica': 3,
         'Welliko': 1,
         'Pathfinder Health': 4,
         'Quantum Leap Packaging': 3,
         'Murfie': 9,
         'Bluestone.com': 6,
         'Lapio': 2,
         'PowerDsine': 6,
         'CapitaLink Technology Limited': 4,
         '0chain': 3,
         'SurgiQuest': 6,
         'Xeropan': 2,
         'New Wind': 2,
         'Wellbefy': 1,
         'Wuhan Kindstar Diagnostics': 3,
         'Novariant': 3,
         'Picture Protection Services': 1,
         'Vest': 1,
         'Vocera Communications': 8,
         'Wavecell': 5,
         'WinSenga': 5,
         'LendInvest': 16,
         'SERMA Group': 2,
         'TOLREMO therapeutics': 2,
         'Livefyre': 7,
         'Sight-Sense': 1,
         'Ocient': 1,
         'Sonnen': 6,
         'WikiMart.ru': 8,
         'SafeGraph': 3,
         'Evolution Funding': 1,
         'Tinybots': 1,
         'Wote': 1,
         'albo': 3,
         'SCIO Health Analytics': 2,
         'Follica': 4,
         'Passbase': 1,
         'Buzzer Feedback': 2,
         'Year Up': 6,
         'DocMatter': 2,
         'Moduware': 6,
         'Proxy Technologies': 4,
         'i4 Media': 1,
         'Macheen': 5,
         'Remerge': 3,
         'Paratus Clinical': 2,
         'Xiaoguo Culture': 1,
         'Hyper Travel': 1,
         'Indianhead Pipeline Services': 2,
         'Selma Finance': 2,
         'Zantaz Inc': 8,
         'Karus Therapeutics': 7,
         'Newtrade Technologies': 2,
         'NIO': 5,
         'GuruQ': 2,
         'SurgRx, Inc': 6,
         'Workspot': 6,
         'Serpstat': 1,
         'SIWA Biotech': 3,
         'Beleza.Com': 1,
         'PhaseRx': 6,
         'Red Herring': 2,
         'SweepTEQ': 2,
         'PamGene': 3,
         'AdvicePay': 3,
         'Cisiv': 6,
         'Lumi': 4,
         'Square Off': 4,
         'Net30': 1,
         'Travelshoot': 3,
         'UVL Robotics': 2,
         'Myki': 4,
         'Banter!': 4,
         'Hitch': 4,
         'Agremo': 2,
         'Debt Resolve': 2,
         'NetBase Solutions': 8,
         'Vimodi': 2,
         'ShareWave': 1,
         'Aihuishou': 5,
         'Heartbeater.com': 1,
         'The Grommet': 5,
         'Dataman': 2,
         'SinglePipe Communications': 3,
         'CN Creative': 1,
         'Yumaroo': 1,
         'RISE Products': 3,
         'Kemia': 4,
         'Wellable': 1,
         'Moesif': 2,
         'Quickflix': 3,

In [54]:
type(funds['raised_amount_usd'].tolist()[0])

float

In [55]:
funds['raised_amount_usd'] = funds['raised_amount_usd'].fillna(0)

In [56]:
sum(funds.loc[funds['company_name']=='Dazo']['raised_amount_usd'].tolist())

40000.0

In [57]:
funds_amount = funds.groupby(['company_name']).sum()

In [58]:
funds_amount.head(2)

,raised_amount_usd,raised_amount,post_money_valuation_usd,post_money_valuation,investor_count
company_name,,,,,
!Creatice,302000.0,0.0,0.0,0.0,0.0
!hey software,10000000.0,0.0,0.0,0.0,2.0

In [59]:
company_names = list(funds_amount.index)
amount_raised = funds_amount['raised_amount_usd'].tolist()

In [60]:
dict1 = dict(zip(company_names, amount_raised))

In [61]:
def get_amount_raised(org):
    try:
        return dict1[org]
    except:
        return 0

In [62]:
orgs1['amount_raised'] = orgs1['company_name'].apply(lambda x:get_amount_raised(x))

## Get Last Funding Status

In [63]:
funds = funds.sort_values(by=['announced_on'],ascending=False)
funds = funds.drop_duplicates(subset=['company_name'],keep='first')

In [64]:
map_funds = dict(zip(funds['company_name'].tolist(), funds['investment_type'].tolist()))

In [65]:
import numpy as np

In [66]:
del map_funds[np.nan]

In [67]:
funds = funds.drop_duplicates(subset=['company_name'],keep='first')

In [68]:
def get_latest_funding_status(org):
    try:
        return map_funds[org]
    except:
        return 'No_funding'

In [69]:
orgs1['last_funding_status'] = orgs1['company_name'].apply(lambda x:get_latest_funding_status(x))
orgs1.head(2)

,company_name,employee_count,Age,location,no_of_founders,no_of_board_members,description,state_code,country_code,status,category_group_list,founded_on,no_of_funding_rounds,amount_raised,last_funding_status
0,Grown Ocean,1-10,4,northeast,NaN,0,Grown Ocean is the mobile app for planning you...,NY,USA,operating,"Apps,Mobile,Software,Travel and Tourism",2015-01-01,1,250000.0,seed
1,Adaptive Media,10000+,7,west,NaN,0,Adaptive Media is an audience and content mone...,CA,USA,closed,"Data and Analytics,Design,Information Technolo...",2012-01-01,1,15000000.0,series_unknown

In [70]:
orgs1.to_csv('orgs_cp1.csv',index=False)

## Give labels

In [71]:
import pandas as pd
orgs1 = pd.read_csv("orgs_cp1.csv")
orgs1.head(2)

,company_name,employee_count,Age,location,no_of_founders,no_of_board_members,description,state_code,country_code,status,category_group_list,founded_on,no_of_funding_rounds,amount_raised,last_funding_status
0,Grown Ocean,1-10,4,northeast,NaN,0,Grown Ocean is the mobile app for planning you...,NY,USA,operating,"Apps,Mobile,Software,Travel and Tourism",2015-01-01,1,250000.0,seed
1,Adaptive Media,10000+,7,west,NaN,0,Adaptive Media is an audience and content mone...,CA,USA,closed,"Data and Analytics,Design,Information Technolo...",2012-01-01,1,15000000.0,series_unknown

In [72]:
def get_label(status):
    if status == 'ipo' or status == 'acquired':
        return 'successful'
    else:
        return 'unsucessful'

In [73]:
orgs1['label'] = orgs1['status'].apply(lambda x:get_label(x))

In [74]:
orgs1.columns

Index(['company_name', 'employee_count', 'Age', 'location', 'no_of_founders',
       'no_of_board_members', 'description', 'state_code', 'country_code',
       'status', 'category_group_list', 'founded_on', 'no_of_funding_rounds',
       'amount_raised', 'last_funding_status', 'label'],
      dtype='object')

In [75]:
orgs1.head(2)

,company_name,employee_count,Age,location,no_of_founders,no_of_board_members,description,state_code,country_code,status,category_group_list,founded_on,no_of_funding_rounds,amount_raised,last_funding_status,label
0,Grown Ocean,1-10,4,northeast,NaN,0,Grown Ocean is the mobile app for planning you...,NY,USA,operating,"Apps,Mobile,Software,Travel and Tourism",2015-01-01,1,250000.0,seed,unsucessful
1,Adaptive Media,10000+,7,west,NaN,0,Adaptive Media is an audience and content mone...,CA,USA,closed,"Data and Analytics,Design,Information Technolo...",2012-01-01,1,15000000.0,series_unknown,unsucessful

In [76]:
orgs1.to_csv('orgs_cp2.csv',index=False)

## Get industry vertical

In [77]:
import random

In [78]:
orgs_final = pd.read_csv('orgs_cp2.csv')

In [79]:
cats = pd.read_excel('/home/rk/raj_data_cb/category_group.xlsx')

In [80]:
category_groups = cats['category_groups'].tolist()

In [81]:
orgs_final['category_group_list'] = orgs_final['category_group_list'].fillna('')
orgs_final['founded_on'] = orgs_final['founded_on'].fillna('')

In [82]:
def get_industry_vertical(categories):
    categories = categories.split(',')
    org_cat = list(set(category_groups).intersection(categories))
    if len(org_cat) == 0:
        return 'others'
    else:
        return random.choice(org_cat)

In [83]:
orgs_final['industry_vertical'] = orgs_final['category_group_list'].apply(lambda x:get_industry_vertical(x))

## Get Age of Company in Months

In [84]:
from datetime import datetime
from datetime import date
from dateutil import relativedelta
def months_between(d1):
    if d1=='':
        return 0
    date1 = datetime.strptime(str(d1), '%Y-%m-%d')
    date2 = datetime.strptime(str(datetime.today()).split()[0], '%Y-%m-%d')
    return (date2.year - date1.year) * 12 + date2.month - date1.month

In [85]:
orgs_final['age_months'] = orgs_final['founded_on'].apply(lambda x:months_between(x))

In [86]:
orgs_final = orgs_final.drop(['state_code','country_code','category_group_list','Age','founded_on','status'],axis=1)

In [87]:
#product_category - empty
#stage - empty
#last_funding_status
#no_of_customer - empty
#no_of_previous_exits_founders - empty
#no_of_investors
orgs_final.head(3)

,company_name,employee_count,location,no_of_founders,no_of_board_members,description,no_of_funding_rounds,amount_raised,last_funding_status,label,industry_vertical,age_months
0,Grown Ocean,1-10,northeast,NaN,0,Grown Ocean is the mobile app for planning you...,1,250000.0,seed,unsucessful,Software,53
1,Adaptive Media,10000+,west,NaN,0,Adaptive Media is an audience and content mone...,1,15000000.0,series_unknown,unsucessful,Internet Services,89
2,Gazelle Lab,1-10,southeast,6.0,0,"Gazelle Lab is a TechStars Network member, men...",1,0.0,series_unknown,unsucessful,Lending and Investments,94

## Number of investors

In [88]:
investments = pd.read_csv('/home/rk/raj_data_cb/investments.csv')

In [89]:
f_rounds_uuids = list(investments.groupby(['funding_round_uuid']).size().index)

In [90]:
f_rounds_count = list(investments.groupby(['funding_round_uuid']).size())

In [91]:
funds.shape

(141532, 21)

In [92]:
funds.head(2)

,company_name,country_code,state_code,region,city,investment_type,announced_on,raised_amount_usd,raised_amount,raised_amount_currency_code,...,post_money_valuation,post_money_currency_code,investor_count,cb_url,company_uuid,funding_round_uuid,created_at,updated_at,investor_names,investor_uuids
176260,SARVA,IND,NaN,Mumbai,Mumbai,seed,2019-05-02,6000000.0,NaN,NaN,...,NaN,NaN,2.0,https://www.crunchbase.com/funding-round/sarva...,d585de6b-b052-443f-87b2-0879d4dcd0fd,ad01fc6e-d29a-408d-9cad-cbeaa4df111a,2019-05-02 04:52:57,2019-05-02 04:52:57,"{""Alex Rodriguez"",""Jennifer Lopez""}","{8797828c-add5-fe2b-b89f-2737abb6aab8,69afcf3c..."
200457,GameClub,USA,NY,New York City,New York,seed,2019-05-02,0.0,NaN,NaN,...,NaN,NaN,NaN,https://www.crunchbase.com/funding-round/gamec...,deb21802-e39d-4715-be37-85a3431a424a,c4756095-7cc4-48b8-9d9e-d2b79f6ba789,2019-04-30 14:45:59,2019-05-02 00:49:34,{},{}

In [93]:
dict1 = dict(zip(f_rounds_uuids,f_rounds_count))

In [94]:
def get_investor_number(uuid):
    try:
        return dict1[uuid]
    except:
        return 0

In [95]:
funds['no_of_investors'] = funds['funding_round_uuid'].apply(lambda x:get_investor_number(x))

In [96]:
funds['investor_uuids'] = funds['investor_uuids'].apply(lambda x:x.replace('{','').replace('}','').split(','))

In [97]:
def count_investors(l):
    l = [l1 for l1 in l if l1!='']
    return len(l)

In [98]:
funds['no_of_investors'] = funds['investor_uuids'].apply(lambda x:count_investors(x))

In [99]:
funds_amount = funds.groupby(['company_name']).sum()

In [100]:
company_names = list(funds_amount.index)
investors = funds_amount['no_of_investors'].tolist()

In [101]:
dict1 = dict(zip(company_names, investors))

In [102]:
def get_inv_number(org_name):
    try:
        return dict1[org_name]
    except:
        return 0

In [103]:
orgs_final['no_of_investors'] = orgs_final["company_name"].apply(lambda x:get_inv_number(x))

## Social Media Presence

In [104]:
organisations['linkedin_url'] = organisations['linkedin_url'].fillna('')
organisations['facebook_url'] = organisations['facebook_url'].fillna('')
organisations['twitter_url'] = organisations['twitter_url'].fillna('')

/home/rk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/rk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/home/rk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [105]:
organisations.loc[organisations['linkedin_url'] !='', 'sm_present'] = 1

/home/rk/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:362: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/home/rk/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [106]:
organisations.loc[organisations['twitter_url'] !='', 'sm_present'] = 1

In [107]:
organisations.loc[organisations['facebook_url'] !='', 'sm_present'] = 1

In [108]:
organisations['sm_present'] = organisations['sm_present'].fillna(0)

/home/rk/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [109]:
dict_sm = dict(zip(organisations['company_name'].tolist(), organisations['sm_present'].tolist()))

In [110]:
orgs_final['social_media_presence'] = orgs_final['company_name'].apply(lambda x:dict_sm[x])

In [111]:
orgs_final.to_csv('orgs_cp3.csv',index=False)

In [112]:
orgs_final.head(2)

,company_name,employee_count,location,no_of_founders,no_of_board_members,description,no_of_funding_rounds,amount_raised,last_funding_status,label,industry_vertical,age_months,no_of_investors,social_media_presence
0,Grown Ocean,1-10,northeast,NaN,0,Grown Ocean is the mobile app for planning you...,1,250000.0,seed,unsucessful,Software,53,0,1.0
1,Adaptive Media,10000+,west,NaN,0,Adaptive Media is an audience and content mone...,1,15000000.0,series_unknown,unsucessful,Internet Services,89,0,1.0

## Get Education of Founders and Co- Founders

In [113]:
jobs = pd.read_csv('/home/rk/raj_data_cb/jobs.csv')
jobs.head(2)

,person_uuid,org_uuid,job_uuid,started_on,ended_on,is_current,title,job_type
0,b42a4f1c-1bed-4390-bce9-0352e5861080,c75dfb95-7099-4597-be14-e31201c65b99,b9ff7ca3-d3bd-4ff6-991d-32cd38710e07,2014-11-01,NaN,t,Vice President and Senior Project Manager,executive
1,7b2fd4b2-ca20-40f2-b6f1-73401022a19d,79609a18-e5ba-5be3-63e7-1fbbf6db8334,8dcdc062-1c0d-47b6-9fc9-1b337a62de99,NaN,NaN,t,Senior Vice President,executive

In [114]:
new_jobs_data=jobs[jobs['title'].str.contains("Founder") | jobs['title'].str.contains("co-Founder") ]
new_jobs_data.head(3)

,person_uuid,org_uuid,job_uuid,started_on,ended_on,is_current,title,job_type
6,fadc1beb-fa25-9cc7-e659-97a2d8da140f,82c41906-0d75-a25a-602d-92bd6eb77e44,1e929162-4287-b175-aff4-3ee90e8d55b3,2016-11-01,2018-07-01,f,Co-Founder and CEO,executive
21,58ed841c-f203-50c1-fd6c-3db3936dc813,011d0f2f-a39b-e667-d270-35c30dac9d47,35bd08aa-5416-6f27-1633-c0f5e999f3aa,2016-01-01,2017-01-01,f,Co-Founder,executive
22,4d931406-39d2-c325-d6e6-4635fc017da6,0da785ca-43a3-bf10-435d-82d9a5ec031a,2acff14c-a2ba-b0bc-d826-bdae460f20df,NaN,NaN,t,"Co-Founder and CFO, COO",executive

In [115]:
new_jobs_data.drop(columns=['job_uuid','started_on','ended_on','is_current','job_type'],inplace=True)
new_jobs_data.head(2)

/home/rk/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

,person_uuid,org_uuid,title
6,fadc1beb-fa25-9cc7-e659-97a2d8da140f,82c41906-0d75-a25a-602d-92bd6eb77e44,Co-Founder and CEO
21,58ed841c-f203-50c1-fd6c-3db3936dc813,011d0f2f-a39b-e667-d270-35c30dac9d47,Co-Founder

In [116]:
degree_data=pd.read_csv('/home/rk/raj_data_cb/degrees.csv')
degree_data.head(2)

,degree_uuid,institution_uuid,person_uuid,degree_type,subject,started_on,completed_on,is_completed,created_at,updated_at
0,7bfee5eb-3565-46ea-a9ec-077308a9396e,4d0a268f-c6d5-7785-163d-c4a98a0f949a,14b6f27c-9de1-4597-9ed8-b51d4ce70626,NaN,NaN,NaN,NaN,f,2018-03-21 21:35:21,2018-03-21 21:35:21
1,c42c4f5c-5f1e-4eea-8f89-b31ff41a8c51,6599f877-7c83-0c47-b05b-dbedd3db7b3a,d4d1e669-379b-1aea-b41e-8183aecb1f22,NaN,NaN,NaN,NaN,f,2017-10-19 14:49:38,2018-02-13 00:02:37

In [117]:
import numpy as np
degree_data=degree_data.replace(np.nan, '', regex=True)

In [118]:
degree_tags=degree_data.degree_type.unique().tolist()

In [119]:
degree_tags.sort()
print(degree_tags[:20])

['', "'A' and 'O' Level", '(B.A', '(B.A) Hons', '(B.A)Hons', '(B.A.', '(B.A.)', '(B.A.),(B.S.)', '(B.A.Sc.)', '(B.Arch.)', '(B.B.A.)', '(B.Com.)', '(B.E.)', '(B.Eng.)', '(B.S.', '(B.S.)', '(B.S.) Electrical Engineering', '(B.S.) Engineering', '(B.Sc.)', '(B.Sc.) Grade3.9/4']

In [120]:
import re
def ret_binned_degree(x):
    x=x.strip(')')
    x=x.strip('(')
    if 'Dr' in x or re.search('phd', x, re.IGNORECASE) or re.search('ph.d', x, re.IGNORECASE) or re.search('doctorate', x, re.IGNORECASE):
        return 'PHD'
    elif re.search('mtech', x, re.IGNORECASE) or re.search('mba', x, re.IGNORECASE) or re.search('master', x, re.IGNORECASE) or re.search('m.tech', x, re.IGNORECASE) or re.search('msc', x, re.IGNORECASE) or re.search('m.sc', x, re.IGNORECASE):
        return  'Master'
    elif re.search('bach', x, re.IGNORECASE) or x.startswith('B') or re.search('bsc', x, re.IGNORECASE):
        return 'Bachelor'
    elif re.search('dipl', x, re.IGNORECASE) or 'Dip' in x:
        return 'diploma'
    elif re.search('assoc', x, re.IGNORECASE) or re.search('AA', x, re.IGNORECASE) :
        return 'associate'
    else:
        return 'others'

In [121]:
degree_data['d_tag'] = degree_data['degree_type'].apply(lambda x:ret_binned_degree(x))

In [122]:
degree_data.head(2)

,degree_uuid,institution_uuid,person_uuid,degree_type,subject,started_on,completed_on,is_completed,created_at,updated_at,d_tag
0,7bfee5eb-3565-46ea-a9ec-077308a9396e,4d0a268f-c6d5-7785-163d-c4a98a0f949a,14b6f27c-9de1-4597-9ed8-b51d4ce70626,,,,,f,2018-03-21 21:35:21,2018-03-21 21:35:21,others
1,c42c4f5c-5f1e-4eea-8f89-b31ff41a8c51,6599f877-7c83-0c47-b05b-dbedd3db7b3a,d4d1e669-379b-1aea-b41e-8183aecb1f22,,,,,f,2017-10-19 14:49:38,2018-02-13 00:02:37,others

In [123]:
len(degree_data[degree_data['d_tag'] == 'others'])

109653

In [124]:
degree_data.shape

(334115, 11)

In [125]:
degree_data=degree_data.groupby('person_uuid', as_index=False).agg(lambda x: ', '.join(set(x.dropna())))

In [126]:
degree_data.drop(columns=['institution_uuid','degree_uuid','degree_type','subject','started_on','completed_on','is_completed','created_at','updated_at'],inplace=True)

In [127]:
degree_data.head(2)

                            person_uuid                  d_tag
0  000020dc-18ce-7f7b-e8c4-8f5d716ad09d  PHD, others, Bachelor
1  00002852-4f2a-473a-ae63-810fa8d3f31f               Bachelor

In [128]:
merged_data = pd.merge(new_jobs_data,degree_data, left_on=['person_uuid'], right_on=['person_uuid'], how='outer')
merged_data.head(2)

,person_uuid,org_uuid,title,d_tag
0,fadc1beb-fa25-9cc7-e659-97a2d8da140f,82c41906-0d75-a25a-602d-92bd6eb77e44,Co-Founder and CEO,NaN
1,58ed841c-f203-50c1-fd6c-3db3936dc813,011d0f2f-a39b-e667-d270-35c30dac9d47,Co-Founder,NaN

In [129]:
len(merged_data['org_uuid'].unique())

151589

In [130]:
merged_data.drop(columns=['person_uuid','title'],inplace=True)
merged_data.head()

                               org_uuid d_tag
0  82c41906-0d75-a25a-602d-92bd6eb77e44   NaN
1  011d0f2f-a39b-e667-d270-35c30dac9d47   NaN
2  0da785ca-43a3-bf10-435d-82d9a5ec031a   NaN
3  2ebc532d-a93f-98b1-7e0d-0dd20d992b4b   NaN
4  881c8903-5bd2-a3bd-ef26-f318439e848c   NaN

In [131]:
fin_data=merged_data.groupby('org_uuid', as_index=False).agg(lambda x: ', '.join(set(x.dropna())))

In [132]:
fin_data.head(2)

                               org_uuid             d_tag
0  00002470-bff7-6226-5800-0ca1b3787b6f  others, Bachelor
1  00007c5c-9260-0dfb-c160-89a416f1a7cc

In [133]:
found = fin_data[fin_data['d_tag'].str.contains(' ')]
print(found.count())

org_uuid    25216
d_tag       25216
dtype: int64

In [134]:
import operator
import math
import collections
def ret_final_tag(x):
    tag_dic_pref={'PHD':5, 'Bachelor':3,'Master':4 ,'diploma':2,'associate':1,'others':0}
    tag_dic_pref_inverse={5:'PHD', 3:'Bachelor',4:'Master' ,2:'Diploma',1:'associate',0:'others'}
    if x=='':
        return 'others'
    l1=x.split(',')
    if 'others' in l1:
        l1.remove('others')
    if len(l1)==0:
        return 'others'
    
    l=[]
    ini=len(l1)
    for itm in l1:
        itm=itm.strip()
        l.append(itm)
    
    freq = {}
    for item in l:
        freq[item] = freq.get(item, 0) + 1
    sorted_x = sorted(freq.items(), key=operator.itemgetter(1))
    sorted_dict = collections.OrderedDict(sorted_x)
    k=(list(sorted_dict.values())[-1])
    
    final_list=[]
    for ky,val in sorted_dict.items(): 
        if sorted_dict[ky]==k:
            final_list.append(tag_dic_pref[ky])
    len_of_finlist=len(final_list)
    final_list.sort()
    
    if len(final_list)==1:
        return tag_dic_pref_inverse[final_list[0]]
    if len(final_list)==2:
        return tag_dic_pref_inverse[final_list[1]]
    if len(final_list)>2:
        return tag_dic_pref_inverse[final_list[-2]]

In [135]:
fin_data['degree_tag']=fin_data['d_tag'].apply(lambda x:ret_final_tag(x))

In [136]:
fin_data.head()

                               org_uuid             d_tag degree_tag
0  00002470-bff7-6226-5800-0ca1b3787b6f  others, Bachelor   Bachelor
1  00007c5c-9260-0dfb-c160-89a416f1a7cc                       others
2  0000b5c1-07dd-aeb6-2b17-eb3d64e652a6            Master     Master
3  0000c0e1-eb00-9281-9a7f-63dfa277e8df                       others
4  0000d497-c93a-eea3-eeb0-a943dfb4f71e          Bachelor   Bachelor

In [137]:
len(orgs_final['company_name'].unique())

107536

In [138]:
orgz=pd.read_csv('/home/rk/raj_data_cb/organizations.csv')
orgz.head(2)

/home/rk/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,company_name,roles,permalink,domain,homepage_url,country_code,state_code,region,city,...,cb_url,logo_url,twitter_url,aliases,uuid,created_at,updated_at,primary_role,type,description
0,0,University of Southern California,company,/organization/beijing-health-guard-biotechnolo...,usc.edu,https://www.usc.edu/,USA,CA,NaN,Los Angeles,...,https://www.crunchbase.com/organization/beijin...,https://crunchbase-production-res.cloudinary.c...,NaN,USC,6590a288-60e6-3821-50bc-3721bcc4351f,2014-03-27 19:36:50,2019-04-20 03:10:33,company,organization,NaN
1,1,Grown Ocean,company,/organization/grown-ocean,grownocean.com,http://www.grownocean.com,USA,NY,New York City,New York,...,https://www.crunchbase.com/organization/grown-...,https://crunchbase-production-res.cloudinary.c...,https://twitter.com/GrownOceanApp,NaN,eea6f58a-b728-d416-7e38-6ca5bad23e2d,2016-04-26 20:25:23,2019-03-25 20:00:23,company,organization,Grown Ocean is the mobile app for planning you...

In [139]:
orgz1=orgz[['company_name','uuid']]
orgz1.head()

                        company_name                                  uuid
0  University of Southern California  6590a288-60e6-3821-50bc-3721bcc4351f
1                        Grown Ocean  eea6f58a-b728-d416-7e38-6ca5bad23e2d
2                              Intel  1e4f199c-363b-451b-a164-f94571075ee5
3                          Intercomp  6681b1b0-0cea-6a4a-820d-60b15793fa66
4   Gruppo Editoriale L'Espresso Spa  e74463f7-94a8-ab7b-ba31-f4cd57a16570

In [140]:
orgz_fin = pd.merge(orgz1,fin_data, left_on=['uuid'], right_on=['org_uuid'], how='right')
orgz_fin.head(2)

,company_name,uuid,org_uuid,d_tag,degree_tag
0,Intel,1e4f199c-363b-451b-a164-f94571075ee5,1e4f199c-363b-451b-a164-f94571075ee5,Bachelor,Bachelor
1,Intercomp,6681b1b0-0cea-6a4a-820d-60b15793fa66,6681b1b0-0cea-6a4a-820d-60b15793fa66,"others, PHD, others, Bachelor",Bachelor

In [141]:
import numpy as np
orgz_fin.isnull().sum()

company_name    16
uuid            16
org_uuid         0
d_tag            0
degree_tag       0
dtype: int64

In [142]:
orgz_fin.shape

(151588, 5)

In [143]:
backup_orgs=pd.read_csv('orgs_cp3.csv')
backup_orgs.head()

,company_name,employee_count,location,no_of_founders,no_of_board_members,description,no_of_funding_rounds,amount_raised,last_funding_status,label,industry_vertical,age_months,no_of_investors,social_media_presence
0,Grown Ocean,1-10,northeast,NaN,0,Grown Ocean is the mobile app for planning you...,1,250000.0,seed,unsucessful,Software,53,0,1.0
1,Adaptive Media,10000+,west,NaN,0,Adaptive Media is an audience and content mone...,1,15000000.0,series_unknown,unsucessful,Internet Services,89,0,1.0
2,Gazelle Lab,1-10,southeast,6.0,0,"Gazelle Lab is a TechStars Network member, men...",1,0.0,series_unknown,unsucessful,Lending and Investments,94,0,1.0
3,HealthAxis Group,251-500,southeast,NaN,0,The HealthAxis Group seeks to reboot healthcar...,1,57000000.0,private_equity,unsucessful,Information Technology,101,1,1.0
4,Wokrr,1-10,west,1.0,0,"Wokrr is based in San Jose, California, United...",1,1111.0,seed,unsucessful,others,41,0,0.0

In [144]:
orgzfin1 = pd.merge(backup_orgs,orgz_fin, left_on=['company_name'], right_on=['company_name'], how='left')
orgzfin1.head()

,company_name,employee_count,location,no_of_founders,no_of_board_members,description,no_of_funding_rounds,amount_raised,last_funding_status,label,industry_vertical,age_months,no_of_investors,social_media_presence,uuid,org_uuid,d_tag,degree_tag
0,Grown Ocean,1-10,northeast,NaN,0,Grown Ocean is the mobile app for planning you...,1,250000.0,seed,unsucessful,Software,53,0,1.0,NaN,NaN,NaN,NaN
1,Adaptive Media,10000+,west,NaN,0,Adaptive Media is an audience and content mone...,1,15000000.0,series_unknown,unsucessful,Internet Services,89,0,1.0,NaN,NaN,NaN,NaN
2,Gazelle Lab,1-10,southeast,6.0,0,"Gazelle Lab is a TechStars Network member, men...",1,0.0,series_unknown,unsucessful,Lending and Investments,94,0,1.0,409e006b-9731-94be-a389-e4f093f6aeb3,409e006b-9731-94be-a389-e4f093f6aeb3,"others, others, Bachelor, Bachelor, others, Ma...",Bachelor
3,HealthAxis Group,251-500,southeast,NaN,0,The HealthAxis Group seeks to reboot healthcar...,1,57000000.0,private_equity,unsucessful,Information Technology,101,1,1.0,NaN,NaN,NaN,NaN
4,Wokrr,1-10,west,1.0,0,"Wokrr is based in San Jose, California, United...",1,1111.0,seed,unsucessful,others,41,0,0.0,90b1f841-706e-6b9e-cc1d-04adbd9f41a3,90b1f841-706e-6b9e-cc1d-04adbd9f41a3,,others

In [145]:
orgzfin1.to_csv('orgs_cp4.csv',index=False)

## Knowledge support Present/Absent

In [146]:
df = pd.read_csv('orgs_cp4.csv')

In [147]:
orgs = pd.read_csv('/home/rk/raj_data_cb/organizations.csv')

In [148]:
investors = pd.read_csv('/home/rk/raj_data_cb/investors.csv')

In [149]:
investors = investors[investors['investor_type'].str.contains("accelerator") | investors['investor_type'].str.contains("incubator")]

In [150]:
investor_uuids = investors['uuid'].tolist()

In [151]:
funding_rounds = pd.read_csv('/home/rk/raj_data_cb/funding_rounds.csv')

In [152]:
import pandas as pd
person_investments = pd.read_csv('/home/rk/raj_data_cb/person_investments.csv')
person_investments.head(2)

,investor_name,roles,domain,country_code_x,state_code_x,region_x,city_x,investor_type,investment_count,total_funding_usd,...,logo_url_y,twitter_url_y,facebook_url_y,linkedin_url,primary_affiliation_organization,primary_affiliation_title,primary_organization_uuid,gender,created_at_y,updated_at
0,Alfonso Villanueva,investor,NaN,USA,CA,CA,NaN,angel,16.0,NaN,...,https://crunchbase-production-res.cloudinary.c...,http://twitter.com/alfvilla,NaN,http://www.linkedin.com/pub/alfonso-villanueva...,PayPal,Global Head Strategy and Office of the CEO,96ab87ca-00b5-2ebc-f218-86262954e320,male,2013-07-23 21:38:11,2018-08-29 21:31:09
1,Alfonso Villanueva,investor,NaN,USA,CA,CA,NaN,angel,16.0,NaN,...,https://crunchbase-production-res.cloudinary.c...,http://twitter.com/alfvilla,NaN,http://www.linkedin.com/pub/alfonso-villanueva...,PayPal,Global Head Strategy and Office of the CEO,96ab87ca-00b5-2ebc-f218-86262954e320,male,2013-07-23 21:38:11,2018-08-29 21:31:09

In [153]:
org_investments = pd.read_csv('/home/rk/raj_data_cb/org_investments.csv')
org_investments.head(2)

/home/rk/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (11,59) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,investor_name,roles_x,domain_x,country_code_x,state_code_x,region_x,city_x,investor_type,investment_count,total_funding_usd,...,linkedin_url,cb_url_y,logo_url_y,twitter_url_y,aliases,created_at_y,updated_at,primary_role,type,description
0,EASME - EU Executive Agency for SMEs,"company,investor",ec.europa.eu,BEL,NaN,11,Brussels,government_office,2602.0,NaN,...,https://www.linkedin.com/company/executive-age...,https://www.crunchbase.com/organization/easme,https://crunchbase-production-res.cloudinary.c...,https://twitter.com/eu_easme,"EASME,Executive Agency for SMEs",2013-03-18 17:36:58,2019-04-01 23:48:57,company,organization,The Executive Agency for Small and Medium-size...
1,EASME - EU Executive Agency for SMEs,"company,investor",ec.europa.eu,BEL,NaN,11,Brussels,government_office,2602.0,NaN,...,https://www.linkedin.com/company/executive-age...,https://www.crunchbase.com/organization/easme,https://crunchbase-production-res.cloudinary.c...,https://twitter.com/eu_easme,"EASME,Executive Agency for SMEs",2013-03-18 17:36:58,2019-04-01 23:48:57,company,organization,The Executive Agency for Small and Medium-size...

In [154]:
org_investments.shape

(345104, 74)

In [155]:
person_investments.investor_type.unique()

array(['angel', 'investment_partner'], dtype=object)

In [156]:
org_investments = org_investments.loc[org_investments['investor_type'].str.contains("accelerator") | org_investments['investor_type'].str.contains("incubator")]

In [157]:
companies_knowledge_support = org_investments['company_name_x'].tolist()

In [158]:
def is_knowledge_support(company):
    if company in companies_knowledge_support:
        return 1
    else:
        return 0

In [159]:
df['knowledge_support'] = df['company_name'].apply(lambda x:is_knowledge_support(x))

In [160]:
df.to_csv('orgs_final.csv',index=False)

In [161]:
df.head()

,company_name,employee_count,location,no_of_founders,no_of_board_members,description,no_of_funding_rounds,amount_raised,last_funding_status,label,industry_vertical,age_months,no_of_investors,social_media_presence,uuid,org_uuid,d_tag,degree_tag,knowledge_support
0,Grown Ocean,1-10,northeast,NaN,0,Grown Ocean is the mobile app for planning you...,1,250000.0,seed,unsucessful,Software,53,0,1.0,NaN,NaN,NaN,NaN,0
1,Adaptive Media,10000+,west,NaN,0,Adaptive Media is an audience and content mone...,1,15000000.0,series_unknown,unsucessful,Internet Services,89,0,1.0,NaN,NaN,NaN,NaN,0
2,Gazelle Lab,1-10,southeast,6.0,0,"Gazelle Lab is a TechStars Network member, men...",1,0.0,series_unknown,unsucessful,Lending and Investments,94,0,1.0,409e006b-9731-94be-a389-e4f093f6aeb3,409e006b-9731-94be-a389-e4f093f6aeb3,"others, others, Bachelor, Bachelor, others, Ma...",Bachelor,0
3,HealthAxis Group,251-500,southeast,NaN,0,The HealthAxis Group seeks to reboot healthcar...,1,57000000.0,private_equity,unsucessful,Information Technology,101,1,1.0,NaN,NaN,NaN,NaN,0
4,Wokrr,1-10,west,1.0,0,"Wokrr is based in San Jose, California, United...",1,1111.0,seed,unsucessful,others,41,0,0.0,90b1f841-706e-6b9e-cc1d-04adbd9f41a3,90b1f841-706e-6b9e-cc1d-04adbd9f41a3,NaN,others,0